### ISSUE TITLE
Implement primary CDN cache invalidation for documents

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#5682]
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

Peter curled this and got a CDN miss, which is very odd since this is one of our most popular pages.

**Comment by peterbe** [comment]
I downloaded a list of the ~100 most popular pages from Google Analytics 
Then ran them through this: https://gist.github.com/peterbe/866811f652a606bc951d28859e06508c

The output is appalling:

```
Hit from cloudfront count: 5 median: 96.0ms
Miss from cloudfront count: 96 median: 321.5ms
```

I don't think there's much to be said. But it goes to show that the CDN cache miss problem isn't just something for rarely visited pages but for "all" pages. 

I know we have other serious problems with web perf that are "CPU bound" but it certainly wouldn't hurt to improve 95% of the pages with a 200ms boost. 

All we need to do is to write a transform function here: https://github.com/mozilla/kuma/blob/d346d0f90bf8e0dfbdc5e6ed8fae1d9236902a50/kuma/settings/common.py#L1907-L1919
Actually the work consists of:

1. Write a transform function (basically turn the document url  + "/index.html")
2. Test that it works if configured using a real AWS
3. Change the CloudFront TTL from 5min to 15min to 1h to 24h. If the invalidation code is solid, we can ramp up more and more. 
4. Sipping Pina coladas

**Comment by peterbe** [comment]
From @callahad on Slack:

The first run:
```
Hit from cloudfront count: 3 median: 136.4ms
Miss from cloudfront count: 98 median: 597.7ms
```

```
Second run:
Hit from cloudfront count: 98 median: 138.2ms
Miss from cloudfront count: 3 median: 943.5ms
```

**Comment by schalkneethling** [comment]
> I know we have other serious problems with web perf that are "CPU bound" but it certainly wouldn't hurt to improve 95% of the pages with a 200ms boost.

My thinking exactly in general.

**Comment by schalkneethling** [comment]
First run:

```
Hit from cloudfront count: 6 median: 763.1ms
Miss from cloudfront count: 93 median: 1052.3ms
RefreshHit from cloudfront count: 2 median: 1922.1ms
```

Second run:

```
Hit from cloudfront count: 84 median: 574.1ms
Miss from cloudfront count: 17 median: 1309.7ms
```

**Comment by atopal** [comment]
Our experiment was targeted at the 90th percentile. At the time that was 4.7s, and yeah, we didn't see any improvement for that. When you go to [the spreadsheet that has been tracking Real User Metrics](https://docs.google.com/spreadsheets/d/1e2_481_W3EZV4CNOp34zqSH2Uc8jJf9ynWkYjtnK_38/edit#gid=1527064796) since last year you can see all the data.

That said, you can clearly see on that chart that there was an improvement, but it was only for the median not the 90th percentile. It went from 1.6s to 1.4s. We always knew we wanted to get to invalidation on demand at some point, but making very fast connections outside of China even faster was not the goal, so we didn't prioritize an increased TTL. It was not a low hanging fruit at the time, but if it is now, we should discuss that.

**Comment by peterbe** [comment]
Can we just close this? 
In Yari we'll go for the jamstack which means there's no gain at all in anything but long TTLs on the CDN caching. So there we're going to get those 200-400ms for free to boot. 
There's clearly lack of interest in making Kuma faster at the moment.

**Comment by peterbe** [comment]
Sorry. I meant it as a question. Pressed the wrong button. Considering that this is assigned to @escattone I'll let him decide if it's worth it.
