### ISSUE TITLE
New frontend: reword the "Edit in wiki" button as it does not open an editing tool

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#5807]
The wording of the "Edit in wiki" button is partly misleading. Even though the icon is a pen and the verb is an action, the page I'm seeing next does not allow me to edit something.

I need to click on "Edit" again to be able to edit the document.

There are some important features which are still available from wiki.developer.mozilla.org/ (e.g. history access, "watching" features, etc.) so I'm not sure I'd like the current "Edit in wiki" to simply open the editing interface (thus hiding the aforementioned features).

It's also difficult to me to come up with a suitable name but I think that:
* "Switch to wiki" (with the pen icon)
* "View in wiki mode" (with some arrow or the pen icon)
would be better alternatives

**Comment by tobinmori** [comment]
@atopal @chrisdavidmills any opinions on this one?

**Comment by chrisdavidmills** [comment]
I did find it a little jarring and annoying to suddently have to click twice before I can edit a page instead of once; the language won't make much difference to me because I know where the edit button is an what it does.

For a new contributor however, this could be rather confusing. Maybe something like "Switch to editable mode"?

BTW, I'm currently using `https://developer.mozilla.org` (not `https://wiki.developer.mozilla.org`), and I am now able to click the edit button once and go straight to the CKEditor interface to edit the page. Is this some kind of special version because I'm an admin or something? I thought you'd reverted the update because of some kind of problem.

**Comment by escattone** [comment]
> BTW, I'm currently using `https://developer.mozilla.org` (not `https://wiki.developer.mozilla.org`), and I am now able to click the edit button once and go straight to the CKEditor interface to edit the page. Is this some kind of special version because I'm an admin or something? I thought you'd reverted the update because of some kind of problem.

Yeah, we reverted the "launch" of the new `beta` domain, so now `https://developer.mozilla.org` is back to being the same as `https://wiki.developer.mozilla.org`.

**Comment by chrisdavidmills** [comment]
> Yeah, we reverted the "launch" of the new beta domain, so now https://developer.mozilla.org is back to being the same as https://wiki.developer.mozilla.org.

Ah, good to know.

**Comment by peterbe** [comment]
Another option is that clicking it once, opens up a tool-tip looking thing (similar to how you switch languages) that offers likes like "Switch to wiki" or "Edit document" or "View history".
