### ISSUE TITLE
CTA to file an issue with errorBoundry

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#5971]
I was wondering, should we include a call to action when an error boundary is triggered asking our users to report the issue to us via Github?

Something like:

An unhandled error occurred in the application. We apologize for the inconvenience! You can [notify the development team by opening an issue](https://github.com/mozilla/kuma/issues/new/choose) on our Github repository. Thank you for using MDN Web Docs.

Thoughts?

**Comment by atopal** [comment]
We can see all of the errors in GA already together with their frequency. What would be the purpose of asking them to file an issue? Maybe a way for them to follow along and be notified when it's fixed?

**Comment by schalkneethling** [comment]
Everything @peterbe said :) plus, it gives the user an opportunity to provide us with extra context that can vastly improve debugging and allow us to more quickly fix problems.

**Comment by atopal** [comment]
Let's handle the low hanging fruit first. Turning this on now, could lead to hundreds of issues filed in the next few weeks, and we'd spend a lot of time just triaging. After that we should re-evaluate. There is benefit in making it easy to file issues, but that has to be weighed against the time spent triaging. One-off issues will happen, and it might be better to ask people to reload the page rather than a one click solution to file an issue we'll then try to reproduce.
