### ISSUE TITLE
 Bug 1588413 Consider making the whoami API call at the start of the page load

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#5980]
(In reply to david from comment #0)
> What feature should be changed? Please provide the URL of the feature if possible.
> ==================================================================================
> Congrats on launching the new version of the site! Sorry I left you all with so much work remaining before you could launch it.
> 
> If you aren't planning to put client-side navigation back right away, you might want to consider starting the /whoami API call in one of the scripts up at the top of the page so that there is a better chance that that data is available before DOMContentLoaded
> 
> What problems would this solve?
> ===============================
> This would help prevent or reduce the time  where the Sign in or user avatar is not there and then blinks in.  (With client-side navigation, the header does not re-render and whoami/ is not called, so this jankiness is just visible on the initial load. But without client-side nav, it is visible on every navigation.)
> 
> Who would use this?
> ===================
> -
> 
> What would users see?
> =====================
> -
> 
> What would users do? What would happen as a result?
> ===================================================
> -
> 
> Is there anything else we should know?
> ======================================
> -

![attachment.png](https://images.zenhubusercontent.com/5d2e105ec7368a420fad5b1c/796f3422-91da-4f63-bad8-5bf768208a5d)

**Comment by peterbe** [comment]
Related is the fact that [the `/api/v1/whoami` endpoint is very slow](https://github.com/mozilla/kuma/issues/5955). 
Meaning, even if the `fetch()` call happens at an earlier time, it'll be hundreds of milliseconds until we know the outcome and only then can we swap the "Sign in" for the mugshot. 

Three things we *could* do (in no particular order):

* `sessionStorage` cache the previous `fetch` response
* use a `prefetch` `<link>` header to trigger the fetch earlier
* make it much faster on the server

All three have their disadvantages:

* `sessionStorage` caching won't help you if it's a new tab. It only really helps if you're clicking around in the existing tab. A `localStorage` solution might be better but it never expires so you'd have to encode it with a timestamp or something.

* If the API is slow. E.g. 1s. And this is the list of internal events: 1) prefetch 2) download, parse, execute JS, 3) make the `fetch()` call. Then, it's very likely that it triggers 2 GETs to the API.

* Optimizing the whoami endpoint isn't easy because it can't easily be cached. It depends on feature flags that may or may not depend on a random chance.
