### ISSUE TITLE
Dead links on the callback page of MDN

### ISSUE THREAD

**Issue by raphaelchalicarne** [mdn/kuma#6013]
The french glossary of MDN contains dead links on the ["Callback" page](https://developer.mozilla.org/fr/docs/Glossaire/Fonction_de_rappel). It contains links to examples : 

"Par exemple, notre exemple de cartes géographiques [maps-example.html](https://github.com/mdn/learning-area/blob/master/javascript/apis/introduction/maps-example.html) ([voir aussi en direct](http://mdn.github.io/learning-area/javascript/apis/introduction/maps-example.html))"

and these links redirect to unexisting pages.

**Comment by peterbe** [comment]
@SphinxKnight can you take a look?

**Comment by SphinxKnight** [comment]
_(I'm back _:))__

I fixed the content which was out of sync with the en-US version. Instead of not mentioning any other example (like en-US), I chose to mentionhttps://github.com/mdn/learning-area/blob/master/javascript/asynchronous/introducing/xhr-async-callback.html instead.

@raphaelchalicarne could you confirm it's OK with you?

@peterbe: I cannot close issues on kuma, could you move it to https://github.com/mdn/sprints/issues if this is not closed quickly? (it's a sheer content issue)

**Comment by raphaelchalicarne** [comment]
Thank you @SphinxKnight , it looks good to me

**Comment by peterbe** [comment]
Content issues goes to md/sprints??

**Comment by SphinxKnight** [comment]
@peterbe thanks for closing.
(aside / Re: content issues, I was not sure before commenting earlier and clicked on "Feedback/Report a content problem" (top sidebar of the new front end) and got a link to https://github.com/mdn/sprints/issues/new?template=issue-template.md&projects=mdn/sprints/2&labels=user-report&title=%2Fen-US%2Fdocs%2FWeb%2FJavaScript%2FReference)

**Comment by peterbe** [comment]
I moved that discussion to here: https://github.com/mdn/kuma/issues/6028
