### ISSUE TITLE
Anchor generation while hovering a heading does not work with new front-end

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#6045]
**Summary**
On w.d.m.o, while hovering a heading/title, one could see an icon to click on in order to get the link with the anchor to this heading.
This feature does not seem to exist on the new front-end.

**Steps To Reproduce (STR)**
1. Went on https://developer.mozilla.org/en-US/docs/Web/API/DragEvent
2. Wanted to get a link from the heading "Event types"

**Actual behavior**
No "UI/simple" feature allowed me to get a link with an anchor to this heading.

**Expected behavior**
Something analogous to how w.d.m.o is behaving (ala hovering and clicking an icon)

**Additional context**
Is there anything related to accessibility/hovering (and maybe not being available on touch devices) blocking this/being a reason this is not implemented?

**Comment by peterbe** [comment]
We actually wrote a port of that functionality to the new React site. I believe it never got merged but perhaps @atopal remember why we didn't?

**Comment by schalkneethling** [comment]
@SphinxKnight This feature was removed, unfortunately. The same functionality is technically available using the TOC at the top of the sidebar.

**Comment by SphinxKnight** [comment]
OK, thanks for the workaround and explanation @schalkneethling 
-if there is a specific rationale for the removal available, I would read it-

**Comment by schalkneethling** [comment]
> -if there is a specific rationale for the removal available, I would read it-

The tl;dr is that the original implementation was a performance hog due to all of the DOM manipulation. @peterbe and I discussed it and landed on a better implementation that Peter then implemented. At the time, however, it was decided that spending more time on this was not a good use of our time as the analytics suggested that *very* few users actually use the feature aka, the user benefit is low.
