### ISSUE TITLE
Should we still use React for pages that are not cached?

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6081]
**Summary**
There is a subset of endpoints, for example `/en-US/users/account/signup` or `/en-US/profiles/batman` (there are more), which the CDN treats as "pass-throughs", so in other words their responses are never cached and all cookies are forwarded. Since these endpoints are also rarely used in comparison to the document pages, the question arises if it's worth converting them to the world of React and strictly client-side, user-based customization?

**Rationale**
If we were to decide that it wasn't worth the effort, it might reduce the workload.

**Audience**
Contributors/members of MDN

**Proposal**
Answer the question proposed in the summary.

**Additional context**
See the discussion within https://github.com/mdn/kuma/pull/6057 which starts [here](https://github.com/mdn/kuma/pull/6057#discussion_r341629879) and develops further after that comment.

**Comment by schalkneethling** [comment]
There are some comments that should not be lost on this pull request:
https://github.com/mdn/kuma/pull/6057

Should we transfer those to this issue?

**Comment by atopal** [comment]
Disclaimer: Feel free to ignore my opinion for anything react related, as I'm obviously not well informed. I'm only commenting, because I've seen page size come up a few times, and how code might be downloaded that's then never used. Of course that's not ideal, but as long as that code is not processed (big if), there is essentially no impact on MDN's performance (within reason). MDN's 90th percentile is CPU limited, not bandwidth limited. We know that since we halved the average MDN page size last year from 600kb to 300kb and it had no measurable effect on our performance metrics.

Here's my understanding: We chose React not only because it allows us to use a CDN and still have  customized content, but also because it's a different front-end paradigm that focuses on independent stylable components, because it means we can make use of a vast ecosystem of open source front-end components, instead of having to build everything from scratch, and because there is a large number of front-end developer familiar with React. 

If the above is true, and living in a part jinja templates/part React world doesn't allow us to take full advantage of the above, I think it might behoove us to convert to React fully and deal with the code splitting as necessary. That said, maybe that makes even more sense after removing the wiki part.

**Comment by peterbe** [comment]
> MDN's 90th percentile is CPU limited, not bandwidth limited.

That's exactly why it's so important to control the size of the JS bundles. 
A large JS bundle takes longer to un-gzip, parse, and execute. 5-10 years ago web perf was network bound but these days it's often CPU bound. Yank and main-thread blocking interactions matter a lot to the performance and the happiness of users. 

Near-mandatory reading is: https://v8.dev/blog/cost-of-javascript-2019

An ideal solution is to code-split the React code. Then we get the power of a reactive JS framework with the fine-grained control of a server-side rendered page. 

I'm actually not sure what's best, under the circumstances that our stack is so weird (no sourcemaps, no code splitting, no bundle analyzers, django-pipeline rewriting Webpack outputs). Options:

* Do what we did with the bcd-signalling and manually write a special Webpack entry just for signup, profile view, etc.
* Eat it. Accept that the JS bundle gets fatter and marginally slower which benefits 0.01% of pageviews.
* Leave certain pages in Jinja which means there might be two different ways to make components. 
* Do whatever is absolutely least amount of effort and friction and hope that someday soon we can resolve this once we move for a new front-end.

**Comment by tobinmori** [comment]
Sounds like this can be punted after we drop the Wiki, unless it's causing a major performance drag now?

If we agree on that I can write an issue for this. . .

**Comment by tobinmori** [comment]
The answer to this is yes we will do this down the line, a candidate for an ADR.
