### ISSUE TITLE
Problem with "Graceful asynchronous programming with Promises" article

### ISSUE THREAD

**Issue by rahim-ismail** [mdn/kuma#6091]
I'm trying to follow the instructions here:
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises

But I keep getting this error trying out the example:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///C:/Users/Rahim%20and%20Maria/Desktop/web-projects/coffee.jpg. (Reason: CORS request not http).

The thing is, the live example works, so copied and pasted the source code of the live example into Visual Studio. And I get the same error.  

 I'm really new to all of this and I'm not quite sure what to do

**Comment by chrisdavidmills** [comment]
This is because you can't run fetch operations directly from your local hard drive (i.e. from a file:// URL). You need to run them from a server such as GitHub pages, or a local web server such as MAMP or Python SimpleHTTPServer.

These will both help you:

* https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
* https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Using_Github_pages

**Comment by rahim-ismail** [comment]
Thanks for your response!

**Comment by chrisdavidmills** [comment]
You are welcome!
