### ISSUE TITLE
Require minium length for "explanation" field in BCD signals

### ISSUE THREAD

**Issue by Elchi3** [mdn/kuma#6139]
**Summary**
_What should be changed?_
A minimum length of 10 characters should be required for the "explanation" field in BCD signals

**Rationale**
_What problems would this solve?_
Less spam submissions

**Audience**
_Who would use this changed feature?_
BCD maintainers

**Proposal**
_What would users see and do? What would happen as a result?_
Users would be required to enter a meaningful explanation and hopefully refrain from submitting "fehfs", "test", and other garbage.

**Additional context**
_Is there anything else we should know?_
Was discussed in https://github.com/mdn/sprints/issues/2289

**Comment by peterbe** [comment]
@atopal Do we invoke the Open Participation team to come back and do this kind of maintenance or are we expected to do it ourselves from now on?

**Comment by atopal** [comment]
This is on us from now on Peter, they don't have any resources they can allocate to this anymore.

**Comment by peterbe** [comment]
@Elchi3 I couldn't help but to start looking into it and now I'm almost there with a half-decent solution. 
Ideally, what I'd like to do is something where it displays (underneat the textarea) like "Minimum 10 characters. YOu have typed 8." And it'd vanish once you're above 10 and reappear again when you've typed too much and say "Maximum is 1,000 characters and you have typed 1,001."
But the code is rather complicated and hard to work on so doing that properly would be very hard. 

However, I found a decent middle-ground. You can set `minlength` and `maxlength` on a [`textarea`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#Attributes) and if you combine that with the `required` attribute you can get something decent working. And instead of something fancy that pops up depending on the user typing, I just extended the help text that appears above with some more text. 

<img width="579" alt="Screen Shot 2019-11-20 at 4 06 25 PM" src="https://user-images.githubusercontent.com/26739/69278150-bc075180-0baf-11ea-9639-ac5bcbc85967.png">
*Note the extra sentence about (typo fixed) "Minimum %(min)s and maximum %(max)s characters."*

I also improved the logic that enables/disables the submit button so that it too respects this number. 

And if you type something >0 but <10 and then blur the input this happens:
<img width="584" alt="Screen Shot 2019-11-20 at 4 09 02 PM" src="https://user-images.githubusercontent.com/26739/69278333-1a343480-0bb0-11ea-919d-ab22180b2121.png">

And here's what happens if you type more than 10 characters and then blur the textarea:
<img width="587" alt="Screen Shot 2019-11-20 at 4 10 20 PM" src="https://user-images.githubusercontent.com/26739/69278405-4780e280-0bb0-11ea-88ba-3b21ecd18a00.png">

Implementing a minimum of 10 on the server (Django) is easy but it kinda sucks that you now have to type these things in 2 places. 
```python
# Python
brief_explanation_min = 10
brief_explanation_max = 1000
```
```javascript
// JS
const MIN_BRIEF_EXPLANATION = 10;
const MAX_BRIEF_EXPLANATION = 1000;
```

Let's hope we never forget :)

**Comment by atopal** [comment]
Hey Peter, I appreciate that you want to fix small things quickly, but I wish you'd have waited a bit. This is not a priority, and the report doesn't have all the details to design a solution. When you show people the minimum characters required, those who had put noise in there, will just generate more noise, but in this case it's not a big deal to lose some submissions, since those with less than 10 characters will in most cases not be actionable anyway.

My actual solution for now would have been to update the spreadsheet I dump this into to hide all submissions with less than 10 characters with a column filter.

**Comment by peterbe** [comment]
So it all started innocently by poking to see if there's a quick and simple fix. Then it escalated when I realized there wasn't because of the way the JS is implemented but I did find a really straight-forward compromise. Then, I noticed something. There is 0 test coverage on the Django side. And there's no validation of the mandatory field `explanation`. So you can `curl` submit BCD signals with no explanation and you keep getting `201 Created`. 
Then, to make matters worse, I noticed that all of your `pytest` based unit tests (roughly half of them) leak effects. In particular, Django views with a ratelimit will be succeed or fail depending on what you've done with the `localhost:8000` server and even worse, there might be stuff stuck in the cache when a new test starts that affect in a crazily unpredictable manner. 

Yari or not, we're sticking to Django for a bunch of other non-wiki related state stuff so our Kuma Django stack is worth maintaining. 

In hindsight, the BC signal implementation was very distracting and poorly executed but that's life and here we are. 

I'd rather keep my improvements I have in [my PR](https://github.com/mdn/kuma/pull/6143) but if you guys want, I can undo the client-side changes because, as you said, they were not very planned.
