### ISSUE TITLE
Production images include development libraries

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6168]
While investigating #6167 (updating our Python dependencies), I discovered that our `kuma_base` Dockerfile installs our development requirements:

https://github.com/mdn/kuma/blob/5a9fb57aa304ed0724e7fd1cff89b4540ba0f0de/docker/images/kuma_base/Dockerfile#L103

This means that we're deploying our development dependencies to production. While that shouldn't be directly harmful, it does have the potential to create confusion or result in hidden dependencies.

**Comment by peterbe** [comment]
This is a tricky thing. I've had the same discussion with a lot of people and there's no one clear way. The advantage of installing everything like this, including some direct libs like `flake8` is that devs and CI end up with the exact same copy locally as what gets deployed. That has advantages. 
Having all the extra dependencies also adds weight to the docker image which causes slower times to copy it from Dockerhub to AWS and around inside Kubernetes. But this is probably negligible at our scale. 

Truth be told, I wish there was an env var somewhere that dictates that `pip install requirements/dev.txt` is desired. Then we wouldn't, for example, have to worry about security in things like `pytest`. 

I for one don't worry about it. Other, much smarter docker people, have expressed similar views. 

I think there's bigger fish to fry on the developer experience such as more up-to-date prod db instances, better test coverage, and perhaps some type checking.

**Comment by callahad** [comment]
Agreed, this is a P3 at best.

My greatest concern is that the current separation of `default.txt` and `dev.txt` is a lie. We don't _really_ know what our production dependencies are, because we could potentially be relying on anything pulled in by any of our so-called dev dependencies.

**Comment by peterbe** [comment]
That's a good point! What's the point of having a `dev.txt` if you're not going to bother using it. 

I'm mindful though because I haven't yet seen any *real* problem with having some dev python libs installed in a production container. Since we're using constraints and hashes with `pip` we don't need to worry about some dev lib causing incorrect installation of versions that conflict with the "production packages". 

I'm totally open to ideas why it's dangerous but I'd also be totally open to the idea of putting everything that's in `dev.txt` into `default.txt`.
