### ISSUE TITLE
Switch to Poetry or Pipenv

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6174]
As part of #6167, we should switch from our curated `requirements/*.txt` files to a tool like [Poetry](https://poetry.eustace.io/) or [Pipenv](https://pipenv.kennethreitz.org/).

This will make it easier to audit and maintain our dependencies into the future, and will dramatically ease the upgrade to Django 2 (#6172), and upgrading our other libraries (#6173).

Current plan:

- [x] Spend half a day evaluating each
- [x] Make a specific recommendation (including publishing both branches for comparison)
- [ ] Consensus, merge.

**Comment by peterbe** [comment]
Sorry, but I missed this in review. 
I see that we now have this: https://github.com/mdn/kuma/tree/master/requirements and that's linked to from here: https://kuma.readthedocs.io/en/latest/development.html#managing-dependencies 
But would you mind adding a line or two about how to use `poetry`. 

I think we can link to https://poetry.eustace.io/docs/cli/#add and https://poetry.eustace.io/docs/cli/#update and perhaps just add a line about something like this:

```
To upgrade an existing package, first start a shell in docker-compose:

     docker-compose exec web bash

Then, to, for example, update `requests` type:

    poetry update requests

Then exit the bash shell and commit your changes to the `poetry.lock` file.
```

**Comment by peterbe** [comment]
I'm sure I'll get the hang of this someday but not today apparently.

As a matter of fact, I wanted to try upgrading a single package. Just to get a feel for it and to help you with the mass-upgrading. I entered a docker-compose bash shell and typed: `poetry update requests-mock` (because we have 0.7.0 and [1.7.0](https://pypi.org/project/requests-mock/) is the latest) but all that happened was this: https://gist.github.com/peterbe/5f7d32e19585e5347640cf070ded3938
