### ISSUE TITLE
Move or remove requirements/docs.txt

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6215]
Blocked by #6174 

Once we move to Poetry or Pipenv, we'll be left with a weird little mostly-empty `requirements/` folder in our root, holding only a `README.rst` and `docs.txt`, the Python requirements for building our documentation.

We should fix that by either moving `requirements/docs.txt` to `docs/requirements.txt` or by folding those requirements into our `Pipfile` or `pyproject.toml` (perhaps as [extras](https://poetry.eustace.io/docs/pyproject/#extras)?).

This would be a "good first bug," except it also requires reconfiguring our integration with ReadTheDocs to ensure that https://kuma.readthedocs.io/ still works. And I have no idea who has access to that. 😅

**Comment by peterbe** [comment]
Drive-by-comment; It should probably be `docs/requirements.txt` anyway since that file, if I'm guessing correctly, is exclusively a readthedocs kinda thing and has nothing to do with our web app. We just need to change this line:
<img width="792" alt="Screen Shot 2019-12-06 at 4 08 21 PM" src="https://user-images.githubusercontent.com/26739/70356593-bc0b8080-1842-11ea-94d6-47e19b515c89.png">

**Comment by callahad** [comment]
That'd be it! :)

**Comment by callahad** [comment]
You also just volunteered yourself as someone who has access to our RtD dashboard to change it, when the time comes 😉

**Comment by peterbe** [comment]
> That'd be it! :)

But do you agree this is orthogonal to the post-pip work? If so, I can just take care of this.

**Comment by callahad** [comment]
Could be done on its own now, sure.
