### ISSUE TITLE
P1 - Switch to async GA tag

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6253]
From https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tag

*"The alternative async tag below adds support for preloading, which will provide a small performance boost on modern browsers, but can degrade to synchronous loading and execution on IE 9 and older mobile browsers that do not recognize the async script attribute. Only use this tag configuration if your visitors primarily use modern browsers to access your site."*

That's us!

So, instead of 
```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
```

we switch to 
```
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
```
which means that when the browser sees that second script tag it can start to download the file before it starts executing the (second) script tag.

**Comment by mindy** [comment]
Because we honor DNT, this makes it tricky to correctly implement a script tag that allows for pre-fetching. The script tag needs to be inside `<head />` at the time the page is parsed, so a dynamic solution as presented in the PR (https://github.com/mdn/kuma/pull/6360) will not give us the performance benefit, since the tag gets added to the page too late. 

Schalk also mentioned that support for DNT is dwindling-- [Safari](https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes#3130296) has removed support and the [working group ](https://www.w3.org/2011/tracking-protection/) has retired. 

A couple of options that we could pursue: 

1. Remove support for DNT, which means every page will load analytics unless their browser or browser extensions say otherwise. The tags will be implemented as [Google suggested](https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tag). 

2. Put only the async script tag in `<head />`, which means the analytics code will load for everyone, with the added performance boost. The code that actually creates the tracker is still wrapped in a DNT check, so in theory, nothing should be recorded or sent to Google...

3. Another option is to leave the tag as is. We lose the benefit of preloading the script, but we preserve DNT. 

Please advise @peterbe @tobinmori

**Comment by atopal** [comment]
Note: Even though support for DNT is dwindling, Mozilla is still committed to it. Our legal counsel asked us not to remove support for it, so that's unfortunately not an option at this time.

**Comment by tobinmori** [comment]
I'd say let's try #2, but let me check GA to see if I can find any info on audience breakdown DNT/non-DNT.
