### ISSUE TITLE
Load modal javascript as defer

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6275]
Currently, the JavaScript for the auth modal is marked as `async`. As @peterbe mentions here https://github.com/mdn/kuma/pull/6094#discussion_r344937847, that is not ideal. To be honest, I believe mentally my intent was to mark this as `defer` and not `async`.

We should update it to be `defer`

**Comment by schalkneethling** [comment]
While doing this, we might as well make the following comment in `common.py` more useful:

```
# Multi Auth Switch
```

**Comment by peterbe** [comment]
I would elevate the priority on this because it's disruptive in local development. 
In local development you end up with this:
```html
<script async src="/modal.js"></script>
<script async src="/auth-modal.js"></script>
```
but those two files are not "thread-safe". Periodically (easy to reproduce by refreshing a couple of times) you'll get it that `/auth-modal.js` executes BEFORE `/moda.js` and then you get this:
<img width="524" alt="Screen Shot 2019-12-23 at 3 07 00 PM" src="https://user-images.githubusercontent.com/26739/71381147-53d9d000-25a0-11ea-850a-89914e9e14ed.png">
