### ISSUE TITLE
Yari 1 Renderer Prototype

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6306]
There are more unknowns here than the Github file structure (and other mitigations), so this should probably be investigated first. 

There are may or may not be more complexity here than we realize and determining the feasibility of this is very important. 

Main question: How hard will it be to write a standalone command to output a full rendered page head/body/footer?

Macro rendered HTML (post-Kumascript) -> complete render

**Comment by escattone** [comment]
### User Story
We need to determine the feasibility/complexity of converting the current front-end code (all of the current Sass, CSS, and JS, as compiled and bundled by `django-pipeline`, as well as the document Jinja template that wraps a React SSR call) into a stand-alone CLI that takes the file-based raw HTML for each document as input and produces finished HTML (i.e., including the header and footer). This is the original idea for the front-end for Yari-1. If this is feasible and relatively simple, we could use it as a way to produce finished HTML documents without initially depending-on the more risky, but fully-new, React-app-based front-end that is the final goal (Yari-2).

### Acceptance Criteria
- [ ] A written risk assessment, in terms of feasibility and complexity, that includes a detailed break-down of the tasks required (assumes that a rough prototype will be attempted in order to expose the risk in a concrete way).
