### ISSUE TITLE
Problem navigating  https://developer.mozilla.org site

### ISSUE THREAD

**Issue by Kostenzer** [mdn/kuma#6342]
Hello,

I tried the arrows/ buttons on [https://developer.mozilla.org/nl/docs/Learn/Getting_started_with_the_web/HTML_basisbegrippen](url) Ass well previous as next don't work.  The Overview arrow/button does work. Now I have to navigate using the links left in the window. And that for a site witch explains HTML...etc.

**Comment by escattone** [comment]
This is resolved for https://developer.mozilla.org/nl/docs/Learn/Getting_started_with_the_web/HTML_basisbegrippen. This was a problem with the translated page only. The document slug arguments to the `PreviousMenuNext` macro call needed to reference the translated slugs rather than the English slugs, so I changed this:
```
PreviousMenuNext("Learn/Getting_started_with_the_web/Dealing_with_files", "Learn/Getting_started_with_the_web/CSS_basics", "Learn/Getting_started_with_the_web")
```
to this:
```
PreviousMenuNext("Learn/Getting_started_with_the_web/Bestanden_beheren", "Learn/Getting_started_with_the_web/CSS_basisbegrippen", "Learn/Getting_started_with_the_web")
```

Other pages in this locale are also broken in the same way, e.g. https://developer.mozilla.org/nl/docs/Learn/Getting_started_with_the_web/CSS_basisbegrippen.

**Comment by benjaminmal** [comment]
Hi,

I was about to submit a new issue when I saw this issue. Since the link @escattone says resolved is not, I hope it can help understand the problem, especially my observation at the end of this message.

**Summary**
Some of the 'Next' or 'Previous' button at the beginning or the end of pages are unclickable. We can notice that this bug happen only with certain page with certain language. Sometimes, buttons at the beginning work while buttons at the end don't. 

The hover button text tells that the next page isn't translated, can it redirects to english instead of nothing ? 

**Steps To Reproduce (STR)**

1. Go to [this url](https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/Variables)  
2. Go to the end of the page.
3. Click on "Suivant".

**Actual behavior**
Nothing.

**Expected behavior**
Redirecting to : https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/Math

**Additional context**
This is my user-agent : 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:72.0) Gecko/20100101 Firefox/72.0`

This is a simple test for each language of this page : 

| Language | Url | Bug? | Is next page translated? |
|---|---|---|---|
| English | [Link](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables) | No | Yes |
| Bengali | [Link](https://developer.mozilla.org/bn/docs/Learn/JavaScript/First_steps/Variables) | Yes | No |
| German | [Link](https://developer.mozilla.org/de/docs/Learn/JavaScript/First_steps/Variables)  |   Yes | No |
| Spanish | [Link](https://developer.mozilla.org/es/docs/Learn/JavaScript/First_steps/Variables) | Yes | Incomplete |
| French | [Link](https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/Variables) | Yes | Yes |
| Hebrew | [Link](https://developer.mozilla.org/he/docs/Learn/JavaScript/First_steps/Variables) | Yes | Yes |
| Italian | [Link](https://developer.mozilla.org/it/docs/Learn/JavaScript/First_steps/Variabili) | Yes | No |
| Japanese | [Link](https://developer.mozilla.org/ja/docs/Learn/JavaScript/First_steps/Variables) | No | Yes |
| Korean | [Link](https://developer.mozilla.org/ko/docs/Learn/JavaScript/First_steps/Variables) | Yes | Incomplete |
| Polish | [Link](https://developer.mozilla.org/pl/docs/Learn/JavaScript/Pierwsze_kroki/Zmienne) | Yes | No |
| Portuguese | [Link](https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Vari%C3%A1veis) | Yes | Incomplete |
| Russian | [Link](https://developer.mozilla.org/ru/docs/Learn/JavaScript/%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B5_%D1%88%D0%B0%D0%B3%D0%B8/Variables) | No | Yes |
| Chinese (simplified) | [Link](https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/Variables) | No | Yes |
| Chinese (traditional) | [Link](https://developer.mozilla.org/zh-TW/docs/Learn/JavaScript/First_steps/Variables) | Yes | Incomplete |

**Observations**
We can see that even if the next page is translated, in some case (Hebrew and French) the button doesn't redirect. But when there is no bug, the next page is always translated.

**Comment by chrisdavidmills** [comment]
@benjaminmal The problem you are referring to with the French "Suivant" button was occuring because there was a typo in the path to the "next" page — "Maths" should have been "Math".

I've fixed that, and it now works fine.

These problems generally are occuring when people translate one of the learning pages, but don't update the paths inside the macro calls that generate these buttons. Or when a page is moved (which I think happened in this case — the slug was "/Maths" but that was wrong as per US englash, so we changed it to "/Math"). Unfortunately the macro is brittle that way. The next generation of MDN will have a proper way generate such menus that won't break when these things happen.
