### ISSUE TITLE
Bugzilla: 607442 Cannot display results in Chinese version

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6343]
Ref: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1607442

**Comment by escattone** [comment]
Copied from the bugzilla ticket:

I fixed https://wiki.developer.mozilla.org/zh-CN/docs/Web/API/Event/preventDefault.

There were 3 problems on that page:
- The embedded live sample `{{EmbedLiveSample('Stopping_keystrokes_from_reaching_an_edit_field', 600, 200) }}` was broken. If the text of the header element containing the live sample is translated (see below) the `id` that is automatically generated is changed as well, and since that `id` is used to find the code related to the live sample, the live sample breaks. This can be fixed by adding the `name=X` attribute to the header element, where `X` should match the first argument to the `EmbedLiveSample` macro call (in this case `"Stopping_keystrokes_from_reaching_an_edit_field"`):
   I changed:
   ```
   <h3 id="在编辑域中阻止按键" >在编辑域中阻止按键</h3>
   ```
   to this:
   ```
   <h3 id="Stopping_keystrokes_from_reaching_an_edit_field" name="Stopping_keystrokes_from_reaching_an_edit_field">在编辑域中阻止按键</h3>
   ```
- The embedded live sample `{{EmbedLiveSample("Blocking_default_click_handling")}}` was broken, in the same way as the first case above:
   I changed:
   ```
   <h3 id="阻止默认的点击事件执行">阻止默认的点击事件执行</h3>
   ```
   to this:
   ```
   <h3 id="Blocking_default_click_handling" name="Blocking_default_click_handling">阻止默认的点击事件执行</h3>
   ```
- One of the chunks of JS for the second example was incorrectly changed from a `js` class to an `HTML` class (see below), which I reverted back to the intended `js` class:
   So I changed this:
   ```
   <pre class="brush: HTML">
   <code>var myTextbox = document.getElementById('my-textbox');
   myTextbox.addEventListener('keypress', checkName, false);</code></pre>
   ```
   to this:
   ```
   <pre class="brush: js">
   <code>var myTextbox = document.getElementById('my-textbox');
   myTextbox.addEventListener('keypress', checkName, false);</code></pre>
   ```
