### ISSUE TITLE
The sign up welcome email is too geared towards making Wiki edits

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6365]
I signed up because I wanted to change my view language, track my learning progress, and set up a subscription, etc. I used Google. And got this:

<img width="1032" alt="Screen Shot 2020-01-22 at 1 56 46 PM" src="https://user-images.githubusercontent.com/26739/72931257-87d51c00-3d2b-11ea-836d-a5e26f831ac7.png">

**Comment by peterbe** [comment]
By the way, Who is "Janet Swisher????" (...thinks the person who's just signed up "MDN Web Docs" and never heard of the wonderful Janet. Separate bug?

**Comment by atopal** [comment]
Yeah, this is a compromise see #2425

There is nothing to customize or set up at this point, which is why we need to ship our first incentive soon. At the same time, the only reason to sign up right now is to contribute, so we end up with this compromise.

That said, we should change the IRC part, as that is now not accurate anymore, IRRC.
