### ISSUE TITLE
B - issues in "what are we missing?" section

### ISSUE THREAD

**Issue by luciancic** [mdn/kuma#6374]
I noticed two issues in the Browser Compatibility Table, "what are we missing?" section:
1. If the table row is a deprecated or experimental feature, the word _Deprecated_ or _Experimental_ is appended to the row name. It would be nice to replace it with the thumbs down or flask icon.
2. On some pages, the _next step_ button does not render
[Example page](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel#Browser_compatibility)

![image](https://user-images.githubusercontent.com/17990875/73004488-6466ab80-3dd5-11ea-8f05-d6035699afdf.png)

I am willing to submit PRs for this, if someone can point me in the right direction.
Cheers!

**Comment by Elchi3** [comment]
Luckily, GitHub now allows issue transfers within the same organization. (and kuma has been moved to mdn :tada:)

**Comment by luciancic** [comment]
Thanks for the move. I'll come back to this issue in a few days but I may not be able to tackle the second point without some help.

**Comment by mindy** [comment]
**Item 1** - Can @chinikes or @atopal please verify if this is still an issue? I am not able to replicate it. This is what I am seeing:
<img width="233" alt="icons" src="https://user-images.githubusercontent.com/650/78398114-81331280-75c0-11ea-8b34-d8f868bf22e7.png">

**Item 2** - This is fixed on production. The issue involves a Kumascript macro, [`InterfaceOverview`](https://wiki.developer.mozilla.org/en-US/search?locale=en-US&kumascript_macros=InterfaceOverview&topic=none). What's happening is that, just below the "Properties" heading, there is an HTML element that never gets closed, so it consumes the rest of the content and unintended children suffer from the parent's styles. In this case, it's a max-width of 42rem, making the BCD table far more narrow than other BCD tables. Since there's not enough space for the BCD table to expand, the content ("Next" button) ends up getting pushed down, sometimes outside of the visible container. 

After examining other pages with this macro, and noticing that some have this issue and some don't, there is a simple fix, which is to update the wiki pages from:
`<p>{{InterfaceOverview("WebRTC")}}</p>` to `<div>{{InterfaceOverview("WebRTC")}}</div>`. 

Not exactly sure why changing the element works, but after speaking with Tobin, we decided that it's not worth the time to fix this macro, and proceed with the quick fix. 

I viewed all the pages with [`InterfaceOverview`](https://wiki.developer.mozilla.org/en-US/search?locale=en-US&kumascript_macros=InterfaceOverview&topic=none), and these were the affected pages: 
https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel
https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannelEvent
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection

**Comment by mindy** [comment]
Re: Item 1, never mind I see the issue-- it's in the dropdown.

**Comment by mindy** [comment]
While adding an icon to the dropdown is a great idea, it would require more effort than we have the time for right now. As a compromise, we are going to remove the "Experimental" and "Deprecated" labels from the dropdown.
