### ISSUE TITLE
T - Self-destructing yourself should also take care of Stripe customer records

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6409]
In `kuma.users.views.delete_user` we either delete a user fully (after all the revisions have been moved to "anonymous") or it scrubs the user's profile (e.g. `user.linkedin_url = ''`). 

Soon, a user is also going to have a Stripe record. 

I'm actually not entirely sure of the ramifications of deleting your Stripe records. (I'm not even entirely sure that "Stripe records" mean). 

* If you scrub your profile, should we also tell Stripe to remove the customer record?
* If you **have an active subscription** should we warn about that first, or just cancel it for them?
* If they want to move their contributions to Anonymous and genuinely be wiped from our database, what should we do with any Stripe records? 

I'm sorry that this issue description is rambling. I'm just eager to make sure we don't forget about this new thing that can become a thing. I know that when Ryan and I wrote the core Django code that does the scrubbing/deleting we didn't have Stripe records in mind. But we do have this: https://github.com/mdn/kuma/blob/5bc5e9ff37473d8f1e38ed56c76f1bf005349c0c/kuma/users/views.py#L494

**Comment by escattone** [comment]
@peterbe Great point and questions! I would say we need to resolve this before we can launch the payments feature to the public.

**Comment by tobinmori** [comment]
Good questions and thanks for filing this @peterbe 

I believe @atopal said that we should delete the subscription upon acct deletion, but can you verify @atopal?

This would mean: canceling the Subscription via Stripe API, then deleting the user acct/customer id in MySQL.

Caveat: We need to be VERY sure that the subscription is deleted from Stripe, because once we delete the customer_id we'd have no way of tracking that, aside from looking at DB backups.

**Comment by Gregoor** [comment]
After implementing it I discovered that we already have a working and tested implementation of this exact functionality:
https://github.com/mdn/kuma/blob/345c5412671bcdf031d4bbc2a68b044b616b07c2/kuma/users/signal_handlers.py#L170-L176

Soo, let's close this?

**Comment by tobinmori** [comment]
Oh nice! Closing. . .
