### ISSUE TITLE
T - Define language around user accounts

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6419]
During the first iteration to implement the new sign-up/accounts flow we have run into many instances where our language around profiles, accounts and general use of things like sentence and title-case have been inconsistent.

A lot of this has to do with the fact that we do not have a style guide that defines the tone and style of language used on MDN, but par of this is also just the age of the project itself.

Doing a search over the codebase for `MDN accounts` I get the following: 195 results in 44 files
Doing a search over the codebase for `MDN profile` I get the following: 702 results in 41 files

A *lot* of this is in `.po` file so, it sounds crazier then it really is, but there is clearly a disconnect and inconsistency here.

We should use this opportunity to clean this all up so we are sure we are consistent. Bonus points for documenting it for our future selves :)

@atopal and @malqinneh your input here would be greatly appreciated.

**Comment by malqinneh** [comment]
From my understanding; it _may have_ made sense in the past to use "profile" nomenclature. Editing wikis was the sole purpose of having a "profile" on MDN - for transparency and activity of wiki edits. Public facing information is typically located in a "profile" page. Since the decision to move to Yari / GitHub, and the very low number of new users that sign up who make edits/contributions, an MDN "profile" was no longer applicable and perhaps even broken.

Now that we're exploring premium features and a subscription based model, signing up for and editing an MDN "account" is a more appropriate label. Information one needs to share with a company for them to provide service(s) is typically located in an "account" page.

Having said this, I'm not sure about the implications of updating all instances of "profile" to "account" in our codebase. If it's low-cost with confidence that it will not break/require extended attention, in the spirit of agile, I would advocate for "taking the opportunity to clean it up/maintain consistency" as you have already suggested @schalkneethling.

**Comment by peterbe** [comment]
The Wiki and its "View profile" feature is on death row. But not for many months. That's a hard fact. 
Another hard fact is that when the Wiki dies, there'll most likely not be any vanity display of yourself to the world like there used to be on the Wiki. 

Another interesting curveball to consider is; do users care at all? "I go to sign in" or "I go to sign up" or "I want to change my preferred locale" or "I want to cancel my subscription". 
Honestly, perhaps it's just me and my use of Internet English, but I don't want to create an account. I just want to sign up. 
We should strive towards a language that users find easy to digest and that makes sense to them. What happens behind the scenes or what things are called deep inside `django-allauth` is immaterial. 

Would you rather tell your mom "To donate money to MDN on a monthly basis, you have to create an account". Or, would you prefer to say "To donate money to MDN on a monthly basis, you have to sign in".

My take is: **Let's *not* do a big search-and-replace now.** Instead, question everything and always assume that people don't have time to care and that lowering barriers, with the right language, is a way to improve MDN for them and for us.

**Comment by malqinneh** [comment]
@peterbe how *we* (internally) refer to "profiles" or "accounts" is what @schalkneethling was asking about. How we position "signing up" to MDN visitors is not in focus right now.

**Comment by peterbe** [comment]
Ahaha! I thought we were talking about the kinds of terms and words that we type into the user facing templates. Because I know I've stirred on that before. /me one-track mind. 

Personally, I don't think it matters what we call things behind the scenes but if you guys think it helps, I'll supportive.

**Comment by atopal** [comment]
I might be wrong about it, but I don't think most users care or understand the difference between creating an MDN profile vs creating an MDN account. I'd also standardize on accounts, but I wouldn't go out of my way to change all of it everywhere.

**Comment by schalkneethling** [comment]
Thank you for all the feedback. Here is what I am getting at:

We need to be consistent internally and externally.

I am not advocating for updating the entire codebase to refer to account vs profile. I *am* advocating for choosing terms and language norms and sticking to it going forward. It ensures that things are consistent in terms of the UI and, it makes it easier to talk about and reason about when *everyone* uses the same language.

**Comment by tobinmori** [comment]
@malqinneh @atopal would a defined style guide be useful here for cases like this going forward?

**Comment by atopal** [comment]
Maybe, in almost four years on MDN this has almost never come up. So I'm not sure it's worth the overhead. I'd not be opposed.
