### ISSUE TITLE
Add `npm run test` to pre-commit hook

### ISSUE THREAD

**Issue by mindy** [mdn/kuma#6437]
**Summary**
This would ensure that all Jest tests pass before committing a change, so it's one less thing to remember to do and we will catch the error before Travis CI does. 

**Audience**
Developers working on Kuma 

**Rationale**
I ran into this problem as witnessed in this pull request: https://github.com/mdn/kuma/pull/6426#issuecomment-583259069

**Workaround**
Remembering to run it manually or Travis CI will catch it and the build will fail. 

**Proposal**
This is a request to see what others think about adding `npm run test` to the pre-commit hook. As @schalkneethling mentioned in the above PR, it might make the commit process tedious.

**Comment by peterbe** [comment]
You're free to do whatever you want with your git hooks because, remember, they're not shared. My `.git/hooks/pre-commit` is mine. But I think you're referring to something like `husky` which "forces" everyone to have the same git hooks. Which, by the way, is problematic. 

*I* rarely work on code that would have any effect on `npm run test` so if I had to wait for that on every commit it would be annoying. Also, perhaps you Mindy, rarely edit the Python files so it would often with a waste of time to wait for some git hook that lint checks .py files. 

And as an example of why this is complicated; why `npm run test` and not `pytest kuma/` or `make pythonlint` or both or all?

Another thing that makes things complicated is that it's an anti-pattern to do anything outside of docker. For example, you might have `npm` version 1.2.3 on your machine, and I have `npm` version 2.3.4 on mine but the only true version that matters is the `npm` *inside* docker which might be version 1.9.4. For example, we don't want people to do any `npm` package upgrades with their host `npm` version. Same for `poetry`. 
And there's the rub because inside the docker container we don't have `git`. That's a thing you have on the host only. 

However, instead of using `npm run test` you can actually use `docker-compose exec web npm run test` from your `.git/hooks/pre-commit`. But sadly, because docker is so slow compared to your host machine, it might just be too annoyingly slow. 

**In general, I think we should avoid putting something into `package.json` that causes a git hook to get installed equally for everyone.**

Mind you, in `stumptown-renderer` (soon to be renamed to `yari`) we do use `husky` which installs a pre-commit that runs: `pretty-quick --staged`
But that's a bit different because `stumptown-renderer`  is 100% JavaScript and `pretty-quick` is extremely fast compared to something like running tests. (`pretty-quick` just runs `prettier` on the files staged for change in git)

**Comment by mindy** [comment]
Thanks for all of that context @peterbe. I think I used the wrong term, which is confusing-- you're right, I was referring to `husky`. I was suggesting to add it to the `precommit` script in package.json: 
`"precommit": "npm run eslint && npm run stylelint && npm run pretty-staged"` 

With the existing test suite it would add about 5s and that number would (hopefully) only grow as more tests are added. I don't mind waiting, since I only mostly work on front-end code that might affect it and would rather catch it sooner, without having to remember to run `npm run test` each commit. 

But I hear your point about the annoyance of making everyone have to run this and it's probably best to leave it out. I'm going to look into `.git/hooks/pre-commit`, since I've never configured them before to see how I can incorporate this in there.
