### ISSUE TITLE
Subscript and italics in preformatted text shows up in WYSIWYG editor, but not when published

### ISSUE THREAD

**Issue by FlyOrBoom** [mdn/kuma#6468]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details
### [Link to article](https://wiki.developer.mozilla.org/en-US/docs/Web/SVG/Element/feColorMatrix)
WYSIWIG editor, applying the subscript button to the numbers:
![image](https://user-images.githubusercontent.com/31298876/74311148-99568600-4d23-11ea-9e78-bbf7b3ae13de.png)
Published:
![image](https://user-images.githubusercontent.com/31298876/74311165-a7a4a200-4d23-11ea-974b-46895ee184f0.png)

**Comment by atopal** [comment]
Elevated to P1 for Sprint Charlie

**Comment by peterbe** [comment]
> Confirmed — the `<sub>` elements are present in the WYSIWYG, but they get stripped out of the published page.

Not really. They're still there on the read-only site. 
<img width="814" alt="Screen Shot 2020-03-23 at 9 51 41 PM" src="https://user-images.githubusercontent.com/26739/77380048-8e463b00-6d50-11ea-8304-ff078cdf4cb8.png">

I suspect what's going on is that there's some JS code that kicks in on the Wiki viewing page (i.e. not the WYSIWYG preview or the final read-only published page) that transforms the HTML to something and it goes wrong. 

Here's the view-source from the Wiki
<img width="876" alt="Screen Shot 2020-03-23 at 9 54 12 PM" src="https://user-images.githubusercontent.com/26739/77380197-e7ae6a00-6d50-11ea-9ceb-9259ae2a1428.png">
And here's the view-source from the read-only:
<img width="877" alt="Screen Shot 2020-03-23 at 9 54 58 PM" src="https://user-images.githubusercontent.com/26739/77380212-f5fc8600-6d50-11ea-901d-cf58dd3cd230.png">

What some JS on the Wiki does is that it transforms the `<pre>...` tag to this:
```html
<pre class="line-numbers language-html"><code class=" language-html">| R' |     | r1 r2 r3 r4 r5 |   | R |
| G' |     | g1 g2 g3 g4 g5 |   | G |
| B' |  =  | b1 b2 b3 b4 b5 | * | B |
| A' |     | a1 a2 a3 a4 a5 |   | A |
| 1  |     | 0  0  0  0  1 |   | 1 |<span aria-hidden="true" class="line-numbers-rows"><span></span><span></span><span></span><span></span><span></span></span></code></pre>
```
(I got this from the DOM inspector, in the dev tools, when loading http://wiki.localhost.org:8000/en-US/docs/Web/SVG/Element/feColorMatrix)


The ultimate culprit is that, on the Wiki, in `kuma/static/js/syntax-prism.js` it assumes that if a `<pre>` tag doesn't have a class name like `class="brush: css"` that it's `html`. I.e. `<pre>` ==> `html` and `<pre class="brush: html">` ==> `html` and `<pre class="brush: css">` ==> `css`. 
If you remove that assumption, it means it "ignores" doing any fancy Prism stuff, then you get this:
<img width="726" alt="Screen Shot 2020-03-23 at 10 12 27 PM" src="https://user-images.githubusercontent.com/26739/77381111-6b695600-6d53-11ea-8ac0-b7a697b6a37e.png">

A little bit further down on the page, there is actually a block of HTML and that still works:
<img width="689" alt="Screen Shot 2020-03-23 at 10 13 17 PM" src="https://user-images.githubusercontent.com/26739/77381157-86d46100-6d53-11ea-91f8-471b84bce753.png">

The tricky and rather scary thing, is **why did it assume that any block of code that isn't specified otherwise is HTML??** 
What if this "fix" fixes this one page but breaks 100 other ones. 

@a2sheppy @chrisdavidmills @wbamberg @Elchi3  Can you revive some memory about this assumption?

Also, I'm really hoping a quick fix is available rather than extensive research and consensus gathering because previewing in the Wiki isn't a high priority area considering the Yari future and the sheer number of people NOT viewing the Wiki outside the WYSIWYG.

**Comment by peterbe** [comment]
> @a2sheppy @chrisdavidmills @wbamberg @Elchi3 Can you revive some memory about this assumption?

IGNORE ME!

I have discovered the problem. And it's unrelated to what I asked you about. 
The read-only site does very similar things to the wiki site when it "warms up" for `Prism.highlightAll()`. They *both* assume that if nothing specified, it's HTML. 

However, the read-only site has this one extra check that the wiki site doesn't:
```javascript
// Expect each block to have a single text node child which
// holds the code to be highlighted. If there is is more than
// one child or if it is not a text node, then assume that the
// block is already formatted and does not need to be tweaked.
if (
    block.childNodes.length !== 1 ||
    block.childNodes[0].nodeType !== 3
) {
    continue;
}
```

So I think all I have to do is figure out how to do the equivalent in jQuery and we should be good to go on this one.
