### ISSUE TITLE
Server error when trying to delete my account on stage

### ISSUE THREAD

**Issue by Gregoor** [mdn/kuma#6479]
It looks like there is a foreign key constraint blocking deletion of users in some cases. Here's the related sentry error:
> "Cannot delete some instances of model 'User' because they are referenced through a protected foreign key: 'AttachmentRevision.creator'", <QuerySet [<AttachmentRevision: test (file: "Screenshot_6.png", ID: #17085)>]>

https://sentry.prod.mozaws.net/operations/mdn-stage/issues/7271436

**Comment by peterbe** [comment]
What's so bizarre is that there is already a test for this: https://github.com/mdn/kuma/blob/3df115a9ba8d3130094a9007f4e9d668a6f274fe/kuma/users/tests/test_views.py#L1533

**Comment by peterbe** [comment]
I wonder, what happened is that you didn't have any Wiki document revisions, so it didn't even ask if you wanted to donate or scrub your account. But for some reason, you had an AttachmentRevision to your name.

**Comment by Gregoor** [comment]
Also I think I just created the account yesterday and not doing anything in the wiki with it. So I don't even know where that Attachment would've come from 🤔

**Comment by peterbe** [comment]
> Also I think I just created the account yesterday and not doing anything in the wiki with it. So I don't even know where that Attachment would've come from 🤔

Now that's very curious!
Here's the attachment revision that supposedly belongs to your account: https://developer.allizom.org/admin/attachments/attachmentrevision/17085/change/
And here's its attachment itself: https://developer.allizom.org/admin/attachments/attachment/16885/change/
Doesn't say in the Django Admin who the creator is.

**Comment by Gregoor** [comment]
Okay maybe I got things mixed up and I had an account before, that is certainly my screenshot 😕

**Comment by peterbe** [comment]
Either way, it's a bug. And I think I can write a unit test to reproduce it. 

By the way, it's weird that you can't look at who the creator was of an attachment revision in the Django admin. 

I tried going into the Kubernetes Stage cluster but https://github.com/mdn/infra/issues/374

**Comment by peterbe** [comment]
Crap. It's not trivial. If a user has attachments, they need to be treated just like document revisions. I.e. "Do you want to donate them to 'Anonymous' or just scrub your account?"

That means that the UI needs to change too. Annoyingly, that UI needs to change in two places :(

CC @schalkneethling @atopal

**Comment by peterbe** [comment]
For the record, https://github.com/mdn/kuma/pull/6482 takes care of the backend piece. If you have *document* OR *attachment* revisions, it now requires that you make a decision about what to do with your attributions. 

The two UIs that use this backend still needs to get this upgrade. I.e. We determine whether to ask the user what to do based on them having DOCUMENT revisions only. It needs to be both.

**Comment by peterbe** [comment]
By the way, I can totally reproduce it. I created a brand new account and went to the Wiki and clicked to Edit a document. But I never edited the document at all. Instead, I just scrolled down to the bottom and added an attachment and that's it. Then I went into my Edit profile and clicked "Delete account" and it's not asking me what I want to do with my attachment revision(s). 
<img width="794" alt="Screen Shot 2020-02-13 at 11 12 43 AM" src="https://user-images.githubusercontent.com/26739/74454539-0e27de00-4e52-11ea-8d87-eb771f2f178b.png">

**Comment by schalkneethling** [comment]
@peterbe What aspect of the UI needs to change?

I am guessing it needs to not only check on `revisions.count()` and/or `revisions.exists()`?

**Comment by schalkneethling** [comment]
Ah nevermind, I see there is a PR for it already.

**Comment by atopal** [comment]
Is there any case like this currently in the user db? Seems like it would be exceedingly rare in production.
@peterbe I don't understand why the UI would have to change? And I don't understand why it would have to change in two places. Can you elaborate? Since this is most likely such an edge case, I'd just show them the "attribution question UI".

**Comment by schalkneethling** [comment]
> Is there any case like this currently in the user db? Seems like it would be exceedingly rare in production.
> @peterbe I don't understand why the UI would have to change? And I don't understand why it would have to change in two places. Can you elaborate? Since this is most likely such an edge case, I'd just show them the "attribution question UI".

There's already pull requests to remedy this:

- https://github.com/mdn/kuma/pull/6482
- https://github.com/mdn/kuma/pull/6488

The UI portion does not change anything visual, it is merely an additional logic condition added to the template.

**Comment by peterbe** [comment]
> Is there any case like this currently in the user db? Seems like it would be exceedingly rare in production.

It's hard to tell how many people have an attachment but no document revision. 
We know a LOT of people upload things. Hard to tell how many just upload but never edit. We can perhaps make a sprint task to investigate what that means in numbers using the production database. 

A more serious thing was that the code paths used to be like this:

```python
# about to delete the user...
if has_revisions:
    with transaction.atomic():
        if donate_attributions:
             donate()
             delete_user()
        elif scrub_account:
             scrub_user()
else:
    delete_user()
```
That means that users that don't have revisions would be executed without an atomic transaction. And I'm sorry, I should have fixed that in the very first revision. 
As of https://github.com/mdn/kuma/pull/6482/files the WHOLE Django view is now atomic. 

So, what happened in the case of Gregor's account was that we don't know exactly what parts of his account got deleted and which didn't because the order of cascading deletes in the Django ORM isn't easy to know. It clearly crashed on the protected cascade of `AttachmentRevision` but we can't really tell what got deleted before and what didn't get deleted after. 

I think what you're alluding to is that we could have instead chosen to not fix this and leave it broken and just accept a couple of Sentry errors and/or perhaps manually intervening when users email/bugzilla us and the manually set aside the time to investigate and manually edit the production database. 
Mind you, if you don't stay on top of the technical debt and accept a bunch of Sentry errors, it's a downwards spiral because the Sentry errors turns into noise and everyone who could do something about the stability will start to filter it out and ignore almost all errors. 

> @peterbe I don't understand why the UI would have to change? And I don't understand why it would have to change in two places. Can you elaborate? Since this is most likely such an edge case, I'd just show them the "attribution question UI".

It requires no VISUAL changes to templates or JS code. In the previous functionality, it used to say "You have 123 revisions [therefore you need to decide whether to donate or scrub yourself]"
But, in the non-visual part of the template, the business logic for whether to display the form or not was only based on `DocumentRevision`. 

And this logic was in two places. The parent of the modal needed to know this for when it displays the modal. The other fallback page the same. They're different. I think it's fairly clear from the [git diff](https://github.com/mdn/kuma/pull/6488/files).
