### ISSUE TITLE
Add task completion survey to start page

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6522]
**Summary**
We currently can't show the task completion survey on the start page, because it requires jqery and we don't have jquery on the start page anymore. So we either add jquery to the start page or we remove the dependency altogether. 

**Rationale**
We should be showing the task completion survey prompt on all pages we expect MDN users to be on, so we don't bias the results and get a full picture of the issues being experienced.

**Comment by schalkneethling** [comment]
Adding some context around the work I have done and what would be needed to make this work:

https://github.com/mdn/kuma/issues/6068#issuecomment-587060413

**Comment by tobinmori** [comment]
Solution: Add jquery to homepage.

**Comment by peterbe** [comment]
Consider `Cash` instead of jQuery. It's much lighter and actively maintained.

**Comment by peterbe** [comment]
Consider `Cash` instead of jQuery. It's much lighter and actively maintained.

**Comment by peterbe** [comment]
@schalkneethling @mindy  Can you help me understand how this relates to https://github.com/mdn/kuma/issues/6678
If the react document has the same base template as the react home page, does that solve *this* issue?

**Comment by schalkneethling** [comment]
> @schalkneethling @mindy Can you help me understand how this relates to #6678
> If the react document has the same base template as the react home page, does that solve _this_ issue?

Not sure, I will have to have a look if that is the case. My immediate reaction would be no. There is an implementation of the task completion survey in the React codebase but, it is only available in `document.jsx`

The first step with this one would probably be to see if we can simply add it to `landing-page.jsx`
With that said, I do notice that `document` is passed to the task completion survey:

```
<TaskCompletionSurvey document={document} />
```

That means we would also need to implement `fetch` in order to load the `DocumentData`

```
fetch({ locale, slug }: DocumentRouteParams): Promise<DocumentData> {
```

All of this is possible but in the end, the decision around this is based on the importance of having this. Perhaps for this, the lowest effort is https://github.com/mdn/kuma/issues/6522#issuecomment-590450881

**Comment by schalkneethling** [comment]
Looking at `task-completion-survey.jsx` again `DocumentData` is optional:

```
type Props = {
    document: ?DocumentData
};
```

What this seems to mean is that if you do not pass `DocumentData`, the `p`(assuming page) parameter will not be added to the survey URL:

```
if (props.document) {
    surveyURL += `&p=${encodeURIComponent(
        `/${locale}/docs/${props.document.slug}`
    )}`;
}
```

Not sure how much of a deal-breaker that is. @atopal Thoughts?

**Comment by peterbe** [comment]
Surely the old Jinja + jQuery based task completion JS code, when on the home page, didn't have a document either. Actually, it seems the old code just used [`window.location.pathname`](https://github.com/mdn/kuma/blob/master/kuma/static/js/task-completion.js) for the `?p=` parameter to surveygizmo. Seems we can just do the same with `task-completion-survey.jsx` instead of messing with `DocumentData` at all. Then it'll be compatible on the home page. 

I can do that.

**Comment by schalkneethling** [comment]
Added Gregor as reviewer
