### ISSUE TITLE
Iframe example csp error

### ISSUE THREAD

**Issue by BenRussert** [mdn/kuma#6572]
# Request type
- [x] Correction or update

# Details

The example iframe fails to load due to csp error. Looks like it's because the iframe src server returns a csp policy `frame-ancestors: self` and is hosted on `mdn-samples.mozilla.org` while the parent is `developer.mozilla.org`. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

![image](https://user-images.githubusercontent.com/10860657/75120693-91afaf00-564a-11ea-8d21-7a8c39a0d3a4.png)

**Comment by chrisdavidmills** [comment]
@schalkneethling @peterbe Is it possible to change the CSP on the samples server so we can get this example working? It makes me wonder why other examples hosted on the samples server are working, whereas this one isn't.

**Comment by schalkneethling** [comment]
> @schalkneethling @peterbe Is it possible to change the CSP on the samples server so we can get this example working? It makes me wonder why other examples hosted on the samples server are working, whereas this one isn't.

I think Peter or @escattone would be the best people to handle that. I have not worked with the CSP in the past. Also, do we even have a CSP on production? I always thought it was only on staging, and then we only have warnings turned on.

Could this be related to changes to iframes in general? 
- https://docs.google.com/document/d/1iaocsSuVrU11FFzZwy7EnJNOwxhAHMroWSOEERw5hO0/edit#!
- https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes
- https://w3c.github.io/webappsec-feature-policy/

**Comment by escattone** [comment]
@chrisdavidmills @schalkneethling The MDN samples server code is controlled by @a2sheppy with help from @limed on the infrastructure side. Although we don't have CSP enabled on developer.mozilla.org, the MDN samples server specifies a CSP in terms of who can embed its content within an `iframe` (the `frame-ancestors` policy), and since for this endpoint it specifies `'self'`, it's essentially saying that no other sites are allowed to embed this endpoint except the MDN samples server, which of course is off since it defeats the explicit purpose of the server.

I don't know where the code is that defines the `frame-ancestors` CSP for the MDN samples server. @a2sheppy or @limed, can one of you take this issue and resolve it?

**Comment by escattone** [comment]
Update: @limed and I resolved the issue. We changed the `frame-ancestors` CSP directive from `frame-ancestors 'self';` to `frame-ancestors 'self' https://developer.mozilla.org https://developer.allizom.org https://mdn.mozillademos.org;`. The key source in this particular case is `https://mdn.mozillademos.org` because the `iframe` that calls `https://mdn-samples.mozilla.org/snippets/html/iframe-simple-contents.html` is embedded within an `iframe` that calls `https://mdn.mozillademos.org/en-US/docs/Web/HTML/Element/iframe$samples/Example1?revision=1605860`. 

We still need to update [this](https://github.com/mdn/samples-server/blob/9bc55b16983007ec7e66dc4da0fad6f0277fb60a/01-mdn-samples.conf#L30) line of configuration since @limed manually updated the configuration on the samples server in order to resolve the issue quickly.

**Comment by a2sheppy** [comment]
I'm on it, thank you for calling this to my attention, and for taking
care of it while I was unavailable!

Ryan Johnson wrote on 2/24/20 8:24 PM:
> |frame-ancestors 'self' https://developer.mozilla.org
> https://developer.allizom.org https://mdn.mozillademos.org;|

-- 
Eric Shepherd <https://www.bitstampede.com/>
Senior Technical Writer @ Mozilla
MDN Web Docs <https://developer.mozilla.org/>
