### ISSUE TITLE
U - Revise paying subscription copy in user profile 

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6588]
# Epic | Milestones 
Revise paying subscription copy in user profile

# Acceptance criteria
- [ ] For paying subscribers, inside of account settings, the title copy for the [subscription] section should be changed to “You are an MDN member".

# Design
https://share.goabstract.com/80aff1b8-a8da-4250-ab33-f6426d45b2e1?collectionLayerId=39ffb131-60e4-4839-b55c-e5f0d9ad9ba1&mode=design

**Comment by schalkneethling** [comment]
@atopal I have dug into this one.

I would like to be clear about what exactly this issue is all about.

Currently, once you have completed successfully signing up for a subscription, the headline text reads as follows: `You're helping MDN grow`

This issue is to change that copy to read: `You are member #{customer_count}`

Looking at the Stripe  API documentation and reading online there used to be a `total_count` type API query but that has been deprecated https://github.com/stripe/stripe-dotnet/issues/813#issuecomment-441677431

So now, the only way is to do something like this[Thank you do @callahad and @escattone for assisting me in refactoring my original attempt]

```
def get_customer_count():
    last_id = None
    count = 0
    while True:
        customers = stripe.Customer.list(starting_after=last_id)
        for customer in customers.data:
            if not customer.delinquent and customer.subscriptions.total_count > 0:
                count += 1
            last_id = customer.id
        if not customers.has_more:
            break
    return count
```

This works in that it gets the total count but, there are a few issues to be aware of:

1. I do not know how expensive it is to do the above. Perhaps there are ways to cache and/or mitigate the expense 
2. Once you have successfully completed your subscription the banner at the bottom of the edit profile page will always show the following:

![Screenshot 2020-02-28 at 20 52 19](https://user-images.githubusercontent.com/10350960/75578302-404d5880-5a6c-11ea-82c9-05430181bf8a.png)

Now, unless we store that number as part of the user profile/subscription status, it is going to change every time another user successfully signs up for a subscription.

3. While all of the above is technically possible, do you believe the end result provides enough user value to justify the work?

Let me know, thanks!

**Comment by schalkneethling** [comment]
Perhaps that number will be more useful to encourage users to sign up? Instead of just a measure after the fact?

**Comment by callahad** [comment]
Those three issues you raised are spot on. This is __far too expensive__ to do on any sort of a regular basis.

If we want to assign member numbers, we should extend a model in our database to hold that information. Just two columns should be plenty, user.id and an auto-incrementing subscription id, but... this is still more work than _not_ assigning membership numbers.

**Comment by tobinmori** [comment]
+1 to Dan. This seems like a bad idea in terms of implementation. Why not just track an incremented count in our DB, instead of this repetitive calculation? Hitting stripe, not to mention totaling their customer object is probably painfully slow and HTTP traffic/api dependent. 

@atopal - is this feature part of a larger product effort to encourage meeting a defined new customer goal? And, is this necessary for MVP launch?

**Comment by peterbe** [comment]
R- on trying to compute anything based on the `stripe` Python api like this. Even cached. No. 
If we're going to perfect the Subscription now already and added advanced features like this, there are much better ways to accomplish a counter like that. 
What I would do is a simple ORM model like:

```python
class SubscriptionSignup(models.Model):
    user = ForeignKey(User)
    amount = DecimalField()
    date = DateTimeField(auto_now_add=True)
```

**Comment by peterbe** [comment]
Either way, we shouldn't discuss how but assume it's not trivial to add the `“You are MDN member [##]”` piece. Not hard, as in complicated or difficult, just something that'll take time. Definitely more than 2.

**Comment by atopal** [comment]
I don't see the copy change reflected in production.

**Comment by atopal** [comment]
The decision here was to just change the copy. Please see the abstract collection: https://share.goabstract.com/4e420774-5f93-4ff2-b15e-f31eb3e10586

**Comment by schalkneethling** [comment]
There is updated copy in the Abstract document that needs to be added to the relevant template.
