### ISSUE TITLE
E - L10N Mitigations for Yari

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6589]
Three stages of L10N cleanup:

1. Pare down locales
2. Remove cruft
3. Define replacement tools for existing tools

Possible User Stories:
- Content team define required locales so that Dev team can prune
- Create tool that can prune 'bad' content by NLTP and datetime analysis
- Define replacements for Doc Status page and other tools used by translators

**Comment by atopal** [comment]
I don't understand how these two user stories address the workflow question for localizes:
* Content team define required locales so that Dev team can prune
* Create tool that can prune 'bad' content by NLTP and datetime analysis

This seems like the important one:
* Define replacements for Doc Status page and other tools used by translators
but I'd rather focus it on the workflow, not jus the tools used.

**Comment by peterbe** [comment]
The discussion about paring down is just optimizations that benefit Yari "internally". Mind you, getting rid of outdated docs (never localized, or just very outdated) will directly bring benefit to users who stumble on them. 

To me, the most important topic for me is to replace Doc_status with some/any tool that lists which documents, in your locale, that are officially behind their parent in terms of git commits.
