### ISSUE TITLE
U - Content team define required locales so that Dev team can work with a smaller dataset

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6590]
**Description**
Step one to get moving on localized content would to prune existing content, so we have a small as dataset as possible, for a few reasons: reducing the dataset means less edge cases; it also means any tools that we write will run a lot faster. 

To that end, it'd be great to start with as small a dataset as possible. A good first step would be to determine what localized content we don't even need to worry about.

**Comment by peterbe** [comment]
I would advise we give this issue the minimal effort possible. Two reasons:

* One thing I learned from the L10n peeps in Berlin 2020 was that they thought it was very "offensive" to delete locales. No crisp explanation could be given by Lobo or Jeff but we can easily speculate that it's a lot more "community'y" and "image" rather than technical merits. I think they think that having >0 involvement with some minority locale is a door-opener to an exciting and growing relationship. 
* Look at https://peterbe.github.io/mdn-sitetree/ Suppose you make a bold and big effort to kill the bottom 10 locales completely. (See point above). That would reduce the *total* number of documents by 1%. 

Contrast that with the much more promising idea of using natural language processing which has the potential to kill 20% without hurting anybody's feelings.

**Comment by tobinmori** [comment]
Doing some cleanup and I'm removing this from the Epic, as this task may be premature now.

**Comment by tobinmori** [comment]
Closing as this is no longer seems relevant.
