### ISSUE TITLE
Address MDN performance issue

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6606]
**Summary**
time to interactive examples for 90th percentile has regressed by .3s some time after February 7.

**Steps To Reproduce (STR)**
[see 90th percentile data](MDN time to interactive examples for 90th percentile has regressed by .3s)

**Actual behavior**
90th percentile is at 3.7s

**Expected behavior**
90th percentile should be at 3.4s

**Additional context**
_Is there anything else we should know?_

**Comment by callahad** [comment]
Here are the deployments that happened around the time that this issue cropped up:

- 2020-01-31 0a7422746b99ca63253190d28fb067a48b8b259d
- 2020-02-06 f48f3fd3e448d169a3ffca4b642cf27821eee8fa
- 2020-02-11 c41c71b49493b617582bacfd20ae4bc98534113d
- 2020-02-12 9aea0ed37d395acf1a4d907b00b09e25acc9c935
- 2020-02-13 777867931247a64cee832e7c7e66a95a709ba2bf
- 2020-02-20 79abfd35af504d1ea8c0f36e7cee20a96011b915

The issue definitely _was not_ happening prior to Feb 6th, and definitely _was_ happening by February 13th. If the regression was caused by a change to our code, it must have been a change in this range: https://github.com/mdn/kuma/compare/f48f3fd3e448d169a3ffca4b642cf27821eee8fa...777867931247a64cee832e7c7e66a95a709ba2bf

**Comment by callahad** [comment]
That range covers the following individual commits. I'm struck through ones that absolutely could not have contributed to this regression.

* ~~f48f3fd3e update sub-modules (#6431)~~
* 669974eb4 Make BCD Signaling section look more like designs (#6382)
* 4e7db4313 Fix dropdown menu position on RTL languages (#6426)
* d477a407e Add stripe subscription to user profile edit view (#6269)
* ~~37b3e54ba Fix deprecation warnings for logger.warn() (#6434)~~
* ~~727f0d90b Update pytest (3.1.3 -> 3.6.4) (#6433)~~
* ~~53b75131e add black as dev dependency + routine updates (#6436)~~
* ~~37b5907ba Update pytest-django (3.1.2 -> 3.4.8) (#6438)~~
* ~~5c5646f49 Fix two deprecation warnings (#6439)~~
* ~~345c54126 Use Black to format Python code (#6447)~~
* ~~566a33347 Straightforward Python dependency updates (#6456)~~
* ~~43113adb1 Update coverage (4.5.4 -> 5.0.3) (#6458)~~
* 0a9abdca2 Align Youtube video embeds with content (#6452)
* ~~1b1bf28da Straightforward Python dependency updates (#6459)~~
* ~~22761e2a2 Upgrade pytest (3.10.1 -> 4.6.9) (#6460)~~
* ~~11a2a36e9 Remove unused custom pytest markers (#6461)~~
* 2ccdedd39 don't index MDN/Doc_status (#6448)
* ~~c41c71b49 update sub-modules (#6465)~~
* ~~e444e9c91 Include Django migrations in linting (#6469)~~
* ~~669ec0a87 Switch to async GA tag (#6463)~~
* 82bffcd45 Add unified git-style diff feature to revise script (#6466)
* ~~f93f13427 Update pytest and pytest-django (#6467)~~
* ~~c1d4fc204 Remove deprecated wiki test (#6476)~~
* ec7425615 Remove jQueryUI, interest and expertise fields - Profile cleanup (#6446)
* 9aea0ed37 link wiki's sign-in to read-only site (#6435)
* a0a9b25f5 minimum 10 characters on bcd signal explanation (#6143)
* 3df115a9b ability to edit whose parent is deleted (#6455)
* ~~a53fd4b86 Small Travis improvements (#6477)~~
* ~~2cae6b7e6 Update to the latest Node LTS (12.13.1 -> 12.16.0) (#6490)~~
* ~~282bdb3b0 don't search on user tags (#6489)~~
* ~~16529cb01 Fix .editorconfig (#6484)~~
* a0918bb8e Do not show avatar transition on signup (#6487)
* ~~777867931 update sub-modules (#6493)~~

Of particular note, we know that "669ec0a87 Switch to async GA tag (#6463)" cannot be at issue because we reverted it and re-deployed last Wednesday, and the performance regression is still present in our data.

**Comment by callahad** [comment]
That leaves us with the much more manageable list of the following 11 commits that we can't trivially exclude:

* 669974eb4 Make BCD Signaling section look more like designs (#6382)
* 4e7db4313 Fix dropdown menu position on RTL languages (#6426)
* d477a407e Add stripe subscription to user profile edit view (#6269)
* 0a9abdca2 Align Youtube video embeds with content (#6452)
* 2ccdedd39 don't index MDN/Doc_status (#6448)
* 82bffcd45 Add unified git-style diff feature to revise script (#6466)
* ec7425615 Remove jQueryUI, interest and expertise fields - Profile cleanup (#6446)
* 9aea0ed37 link wiki's sign-in to read-only site (#6435)
* a0a9b25f5 minimum 10 characters on bcd signal explanation (#6143)
* 3df115a9b ability to edit whose parent is deleted (#6455)
* a0918bb8e Do not show avatar transition on signup (#6487)

**Comment by atopal** [comment]
Confirming that yes, #6601 didn't have a performance impact. Thanks Dan for divining into this and making this issue much more actionable. 

What's the suggestion for next steps here? Do we pick the things that that are easily revertible and try them first? We need at least 1 full day of data to verify the impact.

**Comment by callahad** [comment]
There's a pretty good chance we could exclude half of the commits above, too, but they just require a slightly closer read than that first pass :)

I think the next step is to have two devs hop on Zoom, synchronously read those commits, and come up with a prioritized list of ones we should try reverting.

Unfortunately, this is unlikely to happen this week: Django 2 has been merged and we need to get it deployed ASAP so we're ready for the security patch that's landing Wednesday morning. And then we'll probably need a few days to see if Django 2 itself changes our baseline performance before we can start testing those commits 🙁

**Comment by atopal** [comment]
That schedule works for me. It's important we find the issue and fix it, so we don't end up compounding performance regressions, but it's not time sensitive.

**Comment by callahad** [comment]
Gregor and I spent half an hour reading each commit line-by-line, and there's nothing that we can conceive of impacting frontend performance in any way.

The Stripe (d477a407e41f25f6afa37ef6fa0013da387c2527) and jQuery UI (ec7425615471d93c3a8f6c670103dabd853f0275) commits were the only ones to really touch the frontend in any meaningful way, but both are constrained to the Wiki.

At this point, we think the regression is unlikely to have been caused by changes in Kuma.

**Comment by callahad** [comment]
I don't know where else to look, but perhaps existing Waffle flags or settings were changed in the Django Admin, maybe there was a new deploy of the Interactive Examples service? Or something else entirely?

**Comment by atopal** [comment]
Hmm, we've had something in the soapbox for the last 2 weeks roughly. Maybe that?

**Comment by callahad** [comment]
Could be! Is that scheduled to end any time soon?

**Comment by callahad** [comment]
__NOTE:__ This is measuring _Time to Interactive Examples_, a custom metric that we track, not the more generic "TTI" metric in, say, Lighthouse.

**Comment by tobinmori** [comment]
@atopal will check on soapbox.

**Comment by atopal** [comment]
okay, we have an alternative explanation: Corona
