### ISSUE TITLE
Investigate how we're storing social auth credenitals

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6620]
In discussing #6574, I was wondering what happened when a user completely changes the set of email addresses associated with their GitHub account? Would they still be able to authenticate to MDN, or are we using the email address as a primary key?

(Mainly asking because I know Kuma has a long history of using a bunch of different auth solutions, so our models might be... weird.)

**Comment by tobinmori** [comment]
File an issue after investigation, if it needs one.

**Comment by escattone** [comment]
I tested this locally, by doing the following:
- created an MDN account, let's call it `test`,  via Google, where the Google account has a single email address, let's call it `abc@gmail.com`
- deleted the email address `abc@gmail.com` from the MDN account `test`
- added a new verified email address, let's call it `xyz@other.com`, to the MDN account `test` (because logins to MDN require that one's MDN account must have at least one verified email address)
- logged out and then tried signing-in again via Google -- it worked just fine 🎉 

As far as I can tell, the key used when logging-in via a social provider like GitHub or Google is the Open ID of your specific social provider account. In fact, this was confirmed recently when one of our MDN users, who had created an MDN account months earlier using a GitHub account that he had since deleted, tried signing-in with his new GitHub account. As expected, he was forced to create a new MDN account, since the Open ID of his new GitHub account did not match the Open ID of his prior GitHub account.
