### ISSUE TITLE
T - Improve performance lag of Profile page due to added Stripe data

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6665]
Gregor has noted a 1 second performance hit on the Profile page due to added data from the Stripe.Customer obj; because of this, caching could be added to improve perf.

**Comment by atopal** [comment]
Do we have more information about where the lag comes from? 1s based on what metric? How much time do we think it would take to address the issue?

In general, I'd be hesitant doing performance optimization for something that is relatively rarely used, unless it's a sure thing and a low hanging fruit.

**Comment by peterbe** [comment]
Also, Yari or not, I think we've mentally set our sights on a new Settings page instead of (ab)using the Wiki Edit Profile page.

**Comment by peterbe** [comment]
When we move the payment stuff to the Subscription landing page (that blue area above the FAQ), all of this stuff needs to be rewritten from being Jinja to instead being API + React. 
That means, the landing page will load from the CDN and once loaded, some XHR kicks in and finds out if the user has a subscription and if not, load the Stripe JS SDK. 
Once implemented, we'll surely drop it from the Edit Profile page. 

So this issue is very likely to be moot. Also, extremely few have a subscription and going to the Edit Profile isn't super common compared to googling for `mdn array foreach` :)

**Comment by tobinmori** [comment]
thanks @peterbe. that make sense.
