### ISSUE TITLE
T - Provide subscribers with a static customer number that is incremented upon each new subscription.

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6731]
**Description**

Upon each new subscription signup we need to store a customer number that increments +1 over the previous customer's (most-recent) number. 

This number needs to be static (and not dynamically computed based on a count of customers) for a few reasons:
- the customer should be able to rely on their number as her own.
- X customer's unsubscribe or deletion should not affect other customer Y's number. 
- if we ever gave rewards/prizes for customer no. 100, we would not want the number to be dynamic, as that might disastrous

**Acceptance Criteria**
- [ ] upon customer subscription, a number is calculated and stored in our database
- [ ] this customer number is immutable and unaffected by other customers' subscription cancellations or acct deletions

**Comment by peterbe** [comment]
One thing to think about is that this number will be "An increment of when you subscribed. Any subscription."
If in the future we have something like tiers ("Gold - $100/month, Silver $25/momth, Bronze - $5/month") then that'd be different subscriptions as far as the `UserSubscription` model is concerned but his number here would be across all and any. 

Shall we, as part of this start it off based on the existing 43 users that have a stripe_customer_id. ? So, whoever signs up first after we launch this, they'll become subscriber number `User.objects.exclude(stripe_customer_id='').count() + 1`

**Comment by peterbe** [comment]
Oh and not just that. Of our 43 existing stripe customers, how do we figure out what number they should get? I think we could write a script that goes through the 43 existing customers and for each one, query the Stripe API to see when their subscription started and then use that.

**Comment by peterbe** [comment]
Actually, I dug into this a bit more. The reason I care is that I don't think it's fair that the first new subscriber (once this issue turns into a PR that goes into `master` that goes into production) becomes subscriber number 1. We should respect the roughly 27 (at the time of writing) Stripe customers that have active subscriptions. Or, perhaps respect all the 43 users that have a `stripe_customer_id`. 

I think we ought to write 2 things:

1. Whenever you become a subscriber, if you didn't already have it in your user profile, you get a subscriber increment number. 
2. A script or "migration of sorts" that takes care of the handful of existing customers. 

What we could do is write a migration that, after the `subscriber_number` field on the `User` model is introduced, looks through the list of users that have a non-empty `stripe_customer_id` and then checks each and everyone against Stripe if they have an active subscription. 

Or, even simpler! If we don't care about the *order* of these 27 active subscribers or the order of all 43 users with a `stripe_customer_id` we can simply do something like this:

```python
number = 0
for user in User.objects.exclude(stripe_customer_id='').filter(subscriber_number__isnull=True):
    user.subscriber_number = number + 1
    user.save()
    number += 1
```

Thoughts on this @atopal @Gregoor ?

**Comment by Gregoor** [comment]
Sounds sensible to me, Peter :+1:

Note for the future that we should probably set that subscriber_number within SQL aka `subscriber_number = SELECT MAX(subscriber_number) + 1 FROM auth_users`, to prevent race conditions.

**Comment by peterbe** [comment]
> prevent race conditions.

I didn't think of that! Good idea.

**Comment by atopal** [comment]
Let’s go with those who have a stripe customer id, but order is irrelevant.

**Comment by peterbe** [comment]
@tobinmori @atopal @chinikes I know changing estimates mid-work is logically flawed but that's all we've got. 
This one turned out to be a lot more complex than we first hoped. It has taken a lot of work out of me and my reviewer @Gregoor .

**Comment by tobinmori** [comment]
thanks @peterbe - we can also add new tasks, if that helps?

what do you think the estimate is going to be upped to?

**Comment by peterbe** [comment]
>  we can also add new tasks, if that helps?
> 

Doesn't help. A number incrementor thingy like this needs to be done correctly because of race conditions. So it's all low level and part of the implementation.

> what do you think the estimate is going to be upped to?

I already changed it from a 1 to a 2. 

In my view, it doesn't change anything because all of these estimates are so unrealistic anyway. Sometimes a 1 means 5 days, sometimes it means 15minutes. Again and again, this happens. 
That's because estimates don't have much connection to reality, unfortunately. 

But that's the language of sprinting and the message is "it turned out to be 2x as hard".

**Comment by atopal** [comment]
Peter, the points are helpful when we discuss them not only at the beginning of the sprint. I'd love to understand why this turned out to be twice as hard. If there are things we hadn't thought about initially, can we change the acceptance criteria, reduce the scope or in some other way reduce the complexity? When something goes form an estimated 1 point to an estimated 5 points it might simply not be feasible anymore, and we might decide to drop it. Anyway, doesn't matter for small differences of course, but any larger changes in scope we should be discussing.

**Comment by peterbe** [comment]
> Peter, the points are helpful when we discuss them not only at the beginning of the sprint. I'd love to understand why this turned out to be twice as hard. If there are things we hadn't thought about initially, can we change the acceptance criteria, reduce the scope or in some other way reduce the complexity? When something goes form an estimated 1 point to an estimated 5 points it might simply not be feasible anymore, and we might decide to drop it. Anyway, doesn't matter for small differences of course, but any larger changes in scope we should be discussing.

If you want the technical explanation it's in the PR. 

I'm still not sure there's any point in editing the estimates after the work has started if you're this close to the finish line. It is, without a doubt, hard to pull back when you feel like you're 95% there. Because we're human, I guess. 

The other tricky thing with estimates is that they actually shouldn't be correct or else they're not estimates. Timeboxing is different. But I think we can learn from the fact that what feels like an easy UI change can go much deeper when it involves database changes. So next time, we'll "double" our estimates when it involves data changes.

**Comment by atopal** [comment]
Yeah, to be clear, it's not about having a perfect estimate, it's about having a conversation when things deviate significantly from the initial estimate.
