### ISSUE TITLE
T - Create Designs for Optimized Sidebar for mobile

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6833]
# Task 
T - Create Designs for Optimized Sidebar for mobile

![Table Of Contents (MVP) - Mobile - Light@1x](https://user-images.githubusercontent.com/4819906/79787339-d5562a80-8314-11ea-8adf-5087e393b3ed.jpg)

Add hyperlink in table of contents to jump to [Related topics] on mobile.

**Comment by malqinneh** [comment]
Investigated optimizing sidebar UX/UI on mobile during this past sprint. The following is a recap of the options explored and the proposed recommendation.

**TL;DR**

- Kumascript generating current sidebar on MDN will be costly to modify
- For now, we can keep the current implementation of the sidebar menu and add a link to it from the table of contents (on mobile)

**Expanded thoughts**

Initially we explored having a sequential menu that bakes in the sidebar content within the main website navigation:
![Menu - Mobile - Light - Option 2@1x](https://user-images.githubusercontent.com/4819906/79785214-793dd700-8311-11ea-8059-fd140c602ecf.jpg)
Moving forward with sequential navigation will be a big undertaking considering the ROI is not worth it (low mobile traffic and _potentially_ better UX for Google indexing)

Explored ways to include the sidebar within the menu toggle (without having the navigation be sequential):
![Table Of Contents (MVP) - Mobile - Light@1x](https://user-images.githubusercontent.com/4819906/79785875-98893400-8312-11ea-91dc-cb6f950af164.png)
This solution is significant in cost and, again, may or may not result in improved Google indexing to justify engineering hours.

Unlike the broken navigation/header and breadcrumbs on mobile, current implementation of sidebar is not perfect but it's not broken either. The biggest UX issue being that in order to reach the sidebar, users need to scroll all the way down the page. We thought of adding a link to reach the sidebar (or 'Related topics' as its currently labeled) from the Table of Contents:
![Table Of Contents (MVP) - Mobile - Light@1x](https://user-images.githubusercontent.com/4819906/79786494-8a87e300-8313-11ea-82fc-616c71aa7468.jpg)

Proposed solution should be a quick win for us while gathering more insight on how to best address navigation on MDN. By then, hope we will be past Kumascript so we can implement the solution on Yari instead.

**Comment by malqinneh** [comment]
Closing this out for now, @atopal let me know if I missed something.
