### ISSUE TITLE
Can't create any new pages on MDN

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/kuma#6879]
**Summary**

MDN seems to be broken for me today. When I try to create a new page, it just gives me an ISE.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Go to https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools
2. Select "New subarticle"
3. Enter content
4. Try to save page

**Actual behavior**

ISE

**Expected behavior**

Page should save and display.

**Additional context**

Around the time the site hiccuped and the problem first occurred, I created this page:

https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Complete_toolchain

This is the URL I actually want to use, but now I can't edit it or delete it. When I do, it gives me an ISE.

**Comment by callahad** [comment]
Sentry: https://sentry.prod.mozaws.net/operations/mdn-prod/issues/7876256/

Would be resolved by fixing https://github.com/mdn/kuma/issues/5942

**Comment by callahad** [comment]
Looks like Chris's apostrophes are encoded oddly, or are an exotic character.

![Screen Shot 2020-04-15 at 10 27 28](https://user-images.githubusercontent.com/24193/79325144-92591900-7f08-11ea-9f20-7dc1a3a5de86.png)

**Comment by atopal** [comment]
I was able to publish an article on staging. Chris, can you check whether it would be solved by removing "exotic characters"?

**Comment by callahad** [comment]
Unfortunately, there's a secondary error: whenever page creation fails like this, a Document gets created without any Revisions. Which then totally breaks any ability to further edit that document.

To wit, https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Complete_toolchain is now unusable and uneditable.

That's showing up in Sentry as https://sentry.prod.mozaws.net/operations/mdn-prod/issues/7876284/

...and that's a separate bug we should find and fix, because we should never create a document if we can't also create an initial revision, but also fixing that p3 issue with utf-8 would make all of this moot.

**Comment by callahad** [comment]
We can't delete it either, because all of our code assumes that Documents have Revisions. Attempting to delete triggers https://sentry.prod.mozaws.net/operations/mdn-prod/issues/7876293/ in Sentry.

**Comment by chrisdavidmills** [comment]
For the moment I've just carried on with my work, using the following URL instead: https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

Thanks for investigating, @callahad !

**Comment by escattone** [comment]
@callahad ❤️ Thank you for investigating and reporting the details on this!

@chrisdavidmills I manually deleted and purged `/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Complete_toolchain` from the production database, so I think you should be good to try again.

**Comment by chrisdavidmills** [comment]
@callahad @escattone I'm still getting a problem here, this time with the new page I'm trying to publish my content on:

https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

I've managed to create a page, If I try to publish any new content whatsoever, it instantly gives me an ISE. I just can't work like this.

**Comment by callahad** [comment]
Same deal, new Sentry issue: https://sentry.prod.mozaws.net/operations/mdn-prod/issues/7603074/

> ![Screen Shot 2020-04-15 at 17 27 58](https://user-images.githubusercontent.com/24193/79362472-9011b180-7f3e-11ea-8e09-a4e701fa1801.png)

@atopal Should we consider re-prioritizing #5942?

**Comment by escattone** [comment]
@chrisdavidmills As @callahad noted above, it looks like the content you're trying to save still contains Unicode characters that our MySQL database can't handle.

**Comment by chrisdavidmills** [comment]
Ha, I'm embarrassed now...I had one of these characters in the source — 😱

This is working now.

**Comment by callahad** [comment]
In hindsight, it is weird that these specific characters are triggering
this error.

Needs more investigation. I'd want to know:

- what is the actual Unicode code point for a character that causes this
error

- what is its utf-8 encoding

- what bytes are we actually seeing on our backend

And then asking what kind of error would cause that mismatch

**Comment by peterbe** [comment]
> @atopal Should we consider re-prioritizing #5942?

But I did jump into #5942 on a whim and timeboxed myself to 1 day. [It went badly.](https://github.com/mdn/kuma/issues/6734#issuecomment-605992644) 
I did manage to migrate my MySQL inside docker-compose (!!) but it got much MUCH weirder when trying to replicate the work against a copy of the production database. 

A quick estimate is that it's about 5 full days worth of "sprint estimate" days. So, about a couple of weeks when realistically worked on. 

The horrible truth is that Yari will completely obliterate the problem with Unicode storage **in the wiki** but we still have MySQL for other things: user stuff, BCD signaling comments, payment feedback, (more?)
I did manage to make it so that the [User Profile could use 4-byte unicode](https://github.com/mdn/kuma/issues/6734#issuecomment-605312360) at least. 

Perhaps there's a story to be made about fixing our MySQL for all tables outside the Wiki. 

PS. I don't think you can fix specific columns. You have to fix the whole tables. But you might be able to ignore some tables.

**Comment by callahad** [comment]
I think I may have been too hasty in attributing that weird output in Sentry with the characters that were causing issues; I think Sentry's display is just wonky since all of the characters I've highlighted _should_ work.

On closer inspection of the content body, however, there _was_ an 😱 emoji, which definitely does _not_ fit in MySQL without `utf8mb4`. I suspect removing that one character would have fixed Chris's issues.

(That emoji, U+1F631 Face Screaming In Fear, requires four bytes, `0xf09f98b1`, to store in UTF-8, while our MySQL configuration errors after 3 bytes.)

**Comment by tobinmori** [comment]
Closing, since we already have an issue for this and are aware of this problem.
