### ISSUE TITLE
Should we use the new Stripe Checkout?

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6882]
**Summary**
This is what you get in the Web Console when using the Stripe Checkout (the modal)
<img width="781" alt="Screen Shot 2020-04-16 at 12 07 33 PM" src="https://user-images.githubusercontent.com/26739/79479610-05cb5b00-7fdb-11ea-857b-eb596b31117d.png">

Are we missing out?

**Rationale**
We might be missing better payment options which could lead to more people making a subscription payment. 

**Audience**
PM and Dev. 

**Proposal**
Investigate the worth of the difference and the dev effort?

**Additional context**
@Gregoor is much more familiar with Stripe Checkout.

**Comment by tobinmori** [comment]
Note: Kadir mentioned that there was a few reasons not to change to Stripe Checkout (can't remember - was in intl currency?)

**Comment by peterbe** [comment]
> Note: Kadir mentioned that there was a few reasons not to change to Stripe Checkout (can't remember - was in intl currency?)

Wasn't it EU regulations? 
Or, we can not speculate. @atopal ?

**Comment by atopal** [comment]
The new stripe check-out is a requirement for companies based in the EU because it supports [Strong Customer Authentication](https://stripe.com/en-de/guides/strong-customer-authentication). Currently SCA is not enforced (earliest date is December 31 2020), and even after it's enforced we're likely not affected. 

We can't switch to it right now, because it changes the checkout process from a modal on the merchant's site to a checkout process on stripe.com. It would require a redesign of the payment process on our end. We can do that, but I'd rather not do it now.

**Comment by tobinmori** [comment]
Will close this for now.
