### ISSUE TITLE
T - Investigate BCD tables as a source of perf slowdowns

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6921]
**Description**

We know that lazy loading BCD tables would be helpful in improving perf, but is there anything else we can do to optimize speed. This task is to investigate to see if there is.

**Comment by peterbe** [comment]
For the record, I once built this: https://github.com/mdn/stumptown-renderer/pull/187
It was a fun and fruitful experience. Since then, the code has rotted beyond repair and besides, all that one really did was to lazy load the BCD *data*. If we try again, next time I'd go one step further and lazy load the JS, CSS, and the data. I.e. first, rewrite the BCD component so that when mounted it fetches its own data. E.g. 

```javasscript
function BrowserCompatibilityTable({tableIndex}) {
  useEffect(() => {
    fetch(`./bcd-${tableIndex}.js`).then(...)
  }, []);
}
```
That way, the initial HTML (and its serialize React state (as JSON)) won't have to add weight to the HTML which could slow down first byte and start render. 

Secondly, I would make it so that simply loading the BCD JS bundle at all, is lazy. E.g.

```javascript
// Somewhere in src/document/index.js

const {BrowserCompatibilityTable} = lazy(() => import('./ingredients/browser-compatibility-table'));

...
// Inside the rendering of the document
const [loadBCDTables, setLoadBCDTables] = useState(false);
useEffect(() => {
  if (hasBcdTables(doc)) {
    setLoadBCDTables(true);
  }
}, [doc])
```

That way, only if the document has BCD table(s) does it download the CSS chunk and the JS chunks and the BCD JSON data. 
It's really just a fancy way of staggering upfront work. The saving grace is that the BCD table is NOT needed when rendering without JavaScript and almost always, the BCD table is near the bottom of the page so you don't have to suffer from the page flickering/flashing and jumping as new layouts are calculated. 

Having said all of that, I don't think I'd even want to do anything until we have a way in Yari to build PR branches into their own HTTP2 CDNs.

**Comment by schalkneethling** [comment]
Timeboxed to 1 point

**Comment by peterbe** [comment]
One of the reasons I never bothered experimenting with this in https://github.com/mdn/kuma/issues/6934 was because if you remove the BCD table from the HTML it doesn't actually say much. There's a bunch of JS in the main bundle, in the CSS bundles and in the serialized state for React. Fixing all of those would be hard. And for what? Not have a BCD table? The BCD tables are awesome and a repeating reason why I visit MDN myself as a web developer. 

The right experiment would be to see about doing a 100% lazy load of the BCD tables. I.e. lazy load the .js and the .css and not have it in the SSR rendered HTML at all. That can soon be execute in Yari 2.

**Comment by schalkneethling** [comment]
> One of the reasons I never bothered experimenting with this in #6934 was because if you remove the BCD table from the HTML it doesn't actually say much. There's a bunch of JS in the main bundle, in the CSS bundles and in the serialized state for React. Fixing all of those would be hard. And for what? Not have a BCD table? The BCD tables are awesome and a repeating reason why I visit MDN myself as a web developer.
> 
> The right experiment would be to see about doing a 100% lazy load of the BCD tables. I.e. lazy load the .js and the .css and not have it in the SSR rendered HTML at all. That can soon be execute in Yari 2.

True. I believe the intent was actually the latter i.e. lazy load all the things.

I am also wondering. @atopal do you know If there is still talk about using caniuse as the provider or, have we decided to stick with our own and improve?

**Comment by atopal** [comment]
We will stick with our version for this year at least.
