### ISSUE TITLE
T - Create designs for additional payment options 

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7239]
# Task 
T - Create designs for additional payment options

**Comment by malqinneh** [comment]
[Link to Abstract collection](https://share.goabstract.com/a4a6ac41-1c52-4348-8561-bc5943f85483)

![57F19E09-9802-451E-BE34-6B213C6B37EB](https://user-images.githubusercontent.com/4819906/86040877-c4abea00-ba12-11ea-85ea-794bf98914fa.jpg)

No response from finance team yet. 

@atopal I just pinged them again, hoping we can get confirmation on best practices here so that we're in a good position to pick things back up when we're ready to launch.

**Comment by atopal** [comment]
Thanks Mustafa!
