### ISSUE TITLE
T - Create designs for additional currency options 

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7242]
# Task 
T - Create designs for additional currency options

**Comment by malqinneh** [comment]
[Link to Abstract collection](https://share.goabstract.com/04adb3a6-b643-40de-a2ca-9ed912d9b27d?collectionLayerId=6b10d760-439c-4dfd-8ef0-48c3b75b4774&mode=design)

![ADD3A38A-51AB-4D4D-B22C-B0FD3F911C5A](https://user-images.githubusercontent.com/4819906/86040556-3d5e7680-ba12-11ea-93b7-e9a443d86ca8.jpg)

As per Stripe's support; we can customize the checkout flow to include all of the payment options as shown in the above image (both option 1 and option 2).

@atopal feel free to close this ticket if everything is OK. Otherwise let me know what I can do.

**Comment by atopal** [comment]
Thanks Mustafa!
