### ISSUE TITLE
Cross background of "No support" box in compatibility table hinders readability

### ISSUE THREAD

**Issue by zjopy** [mdn/kuma#7357]
**Summary**
_What is the problem?_

Currently, the red "No support" box in the compatibility table has a cross as background image. This negatively affects readability, because it interferes with the flow of any text in it.

The colors red and green already do a perfectly fine job of signaling "Full support" and "No support". The cross as background image should simply be removed.

As so often with design, the principle "less is more" is true here as well.

For example, take a look at the compatibility table for the [@viewport](https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport) CSS rule with and without the background image.

<img width="1006" alt="Screenshot 2020-07-17 at 16 43 47" src="https://user-images.githubusercontent.com/33468089/87793184-35da0280-c845-11ea-95b8-8c8061852882.png">

<img width="1006" alt="Screenshot 2020-07-17 at 16 44 20" src="https://user-images.githubusercontent.com/33468089/87793218-425e5b00-c845-11ea-9c15-aa4cbdc55d97.png">

Seeing this side by side, it really hurts my eyes to read the table with the cross background. Please remove the cross background image.

**Comment by atopal** [comment]
Hey zjopy, thanks for filing this, the cross background is actually an accessibility feature for color blind people, since red and green can be a challenge to tell apart. I do recognize that this is not a great solution, and ideally we'll be able to redesign the tables to reduce the busyness of the tables and keep accessibility in mind, but we won't be able to do that soon  and can't drop the crossed background for that reason.
