### ISSUE TITLE
Problem with the Hebrew Editing

### ISSUE THREAD

**Issue by igmlom** [mdn/kuma#7542]
Mixing Hebrew and English together.

In the Hebrew version, all the content written in Hebrew, except the things that impossible to translate. So something there is a function with parentheses surrounded by Hebrew, but the parentheses aren't as they would be.

![image](https://user-images.githubusercontent.com/62591311/94927605-304a9b00-04cb-11eb-8714-d4d136f7d6a7.png)

**Comment by igmlom** [comment]
Hi, sorry about the delay.

Take this link for example https://developer.mozilla.org/he/docs/Learn/JavaScript/Asynchronous/Introducing
The interesting thing is the part of the page is alright, and another is not:
This is okay:
![image](https://user-images.githubusercontent.com/62591311/95678676-d470c800-0bd6-11eb-844e-afdc739fe156.png)
This is not:
![image](https://user-images.githubusercontent.com/62591311/95678694-f36f5a00-0bd6-11eb-8663-22d1d565681c.png)

About your question, if I'm using google translate extension it gets all right.

**Comment by peterbe** [comment]
Correct?
```html
<a href="/he/docs/Web/API/Console/log"><code><bdi>console.log()</bdi></code></a>
```

Incorrect
```html
<code>console.log()</code>
```

The first snippet is created using a KumaScript macro:
```
{{domxref("console.log()")}}
```

The second snippet is part of the content itself:
```html
<p>הדפדפן יתחיל להריץ את הקוד, הוא יראה את ה-<code>console.log()</code> הראשון ויריץ אותו. ולאחר מכן ייצור את המשתנה <code>image</code> .</p>
```

So basically, what the Hebrew translator should have done is:
```html
<p>הדפדפן יתחיל להריץ את הקוד, הוא יראה את ה-<code><bdi>console.log()</bdi></code> הראשון ויריץ אותו. ולאחר מכן ייצור את המשתנה <code>image</code> .</p>
```

Because, that's basically what you need to do with Hebrew HTML, right?
Pardon my ignorance on this topic but I'm interested to learn. 

What's super interesting is that Google Translate will automatically get this right? 
I don't quite understand how they do it but it seems the break up the `<p>` tag as the text before and after the `<code>console.log()</code>` and translate each one "independently" without touching the `<code>` tag. 
<img width="982" alt="Screen Shot 2020-10-12 at 9 12 56 AM" src="https://user-images.githubusercontent.com/26739/95750537-4a267380-0c6b-11eb-9a44-801ec3a19ec6.png">

Either way, I suspect the right thing to do is to [fix the Hebrew translation](https://wiki.developer.mozilla.org/he/docs/Learn/JavaScript/Asynchronous/Introducing$edit) as the HTML in question is actually part of the content, and not the platform. 

In the future, we're going to make MDN depend less on humans translating HTML strings and more Google Translate things. So with that in mind, I'll close this for now. 

Thank you!
