### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by alejandrocgf** [mdn/kuma#7599]
I had to create a new GitHub account (with the same username and email) because I could not recover my old one.

My MDN account must be linked to my old GitHub account because I cannot choose my old username alejandrocgf. Instead I got alecgarfer.

Is it possible to link my new GitHub account to my old MDN account so I can use my old username?

Thanks.

**Comment by peterbe** [comment]
I see that your old account was created with the exact same email address as the new one (where you got a new username). So I can vouch for you. But what I need you to do is to delete your NEW account. 
Go to https://developer.mozilla.org/en-US/profiles/alecgarfer/delete
Whilst you do that, I'll rename the OLD username to `alejandrocgf__legacy` so that when you sign up, again, your preferred username will be available. 

Thanks for using MDN!

Let me know if it worked and I'll close this issue.

**Comment by alejandrocgf** [comment]
I deleted my new account.
