### ISSUE TITLE
Galician localization

### ISSUE THREAD

**Issue by ascarida** [mdn/kuma#7663]
I would like Galician to be in the list of locations available on MDN in order to start translating content about HTML, CSS and JS.

:)

**Comment by chrisdavidmills** [comment]
Hi @ascarida !

Thank you for getting in touch with us. I wish I had better news, but we are currently in the process of limiting our localization scope, because so much of the translated content we have on MDN is unmaintained and out of date, and we don't have enough resources to manage the locales we've got.

The following blog post outlines the plan for MDN l10n once we have moved to out new platform: https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/

At this point, I'm afraid to say we would not be prepared to add new locales to the system.
