### ISSUE TITLE
Empty SERP

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/kuma#7756]
While I was researching something on MDN I noticed that some search results come up empty. Take https://developer.mozilla.org/en-US/search?q=media+overview for example:

![empty-serp](https://user-images.githubusercontent.com/3097194/106031824-03e90900-60d0-11eb-8ce5-fff31cc6092e.png)

What's going on here?
Can the situation be improved?

**Comment by peterbe** [comment]
This happens because the document there got included because it contained a match on the `title` **only**. There were no matches at all in the `body` so there can not be any `excerpts`. 
You can see it better here: https://developer.mozilla.org/api/v1/search?q=media+overview (look for the `highlight.body` key on the 6th and 7th result. 

I think what we should do is that if there are no excerpts, we fall back to the document's summary. What do you think about that?

**Comment by Ryuno-Ki** [comment]
Hm, I think, I would rather downrank the result instead (if possible).

**Comment by peterbe** [comment]
A match on the `title` is boosted over a match on the `body`. So there might be a doc that has matches on the body but much worse matches in the title. 
There's also the complexity of the fact that "downranking" is actually influenced by the popularity of the document. So I don't think it's feasible to try to push these down more. They have to appear because the search logic is "INCLUDE IF (MATCH IN TITLE OR MATCH IN BODY)"

**Comment by peterbe** [comment]
One thing I need to consider is to search by the `summary`! If a match matches the summary, I think that should rank a bit higher than a match inside the body.

**Comment by Ryuno-Ki** [comment]
Sounds like a complicated (as in: small tweaks have major impacts) topic.

Can you point me to the current implementation? Or is it for staff only?

**Comment by peterbe** [comment]
> Can you point me to the current implementation? Or is it for staff only?

Implementation? Do you mean the code that executes the search? It's all in Kuma:
https://github.com/mdn/kuma/blob/3474f01b723e10009f61678d2ee67e0696c42868/kuma/api/v1/search/__init__.py#L62-L243

**Comment by Ryuno-Ki** [comment]
Exactly that!

So I can filter with `exclude` and `only` somehow? Interesting.
I feel, this should be hinted somewhere on the search (my suggestion would be on the SERP itself, as it is a way to trim down the results).

**Comment by peterbe** [comment]
I don't understand what you mean by "filter". 
The backend is an implementation detail. We don't make any promises about it. But we will support the front-end.

**Comment by Ryuno-Ki** [comment]
Filter as in: Limit the search results to contain only pages of a certain subtree.
Or exclude archived pages from results.

**Comment by peterbe** [comment]
We will/might add some advanced options like that. Right now, honestly, we're rushing to get away from the old Wiki search. 
It would be nice to be able to do all sorts of fancy parameters, but every parameter because a maintenance burden. So we'll start from the UI and ask what features we really need. Then we'll add that to the back-end and once it's in place we update the UI to allow for these things. 

 Unfortunately, we don't have a search REST API that we document and plan to support. We only have what we necessarily need for the UI.

**Comment by Ryuno-Ki** [comment]
Okay.

Please tag me once the planning of the search API is starting.
Let's get back to the original topic of this issue :-)
